### ISSUE TITLE
Package Request: ISSE

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#1]
See http://isse.sourceforge.net/index.html

Sorta of a unique tool.
Should be easy to build (based on juce).
Doesn't seem to have external dependencies.

**Comment by kvr2007** [comment]
FYI
Some users reported that ISSE compiled as instructed by developers fails to load *.wav files. So some modifications to the source code may still be needed...
https://sourceforge.net/p/isse/tickets/9/

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
