### ISSUE TITLE
Update wineasio depends to allow other versions than wine-rt

### ISSUE THREAD

**Issue by spectromas** [KXStudio/Repository#103]
I use the official winehq repository for wine now rather than wine-rt provided by kxstudio, it seems to have improved a lot since that version, but wineasio from kxstudio is not installable without dragging in wine-rt and removing winehq-stable. Could you update the depends to allow for winehq-*?

**Comment by falkTX** [comment]
you can install wine-staging with wineasio now.

**Comment by aljelly** [comment]
Can you add `winehq-devel` as well please? Wine Staging is currently out of date, and the latest versions of Wine fixes a lot of compatibility problems.

(Perhaps you could also add `winehq-*` so that any Wine works? Or if that's not possible, `winehq-devel` and `winehq-stable`?)

**Comment by SamuelMiller** [comment]
Hi, any plans to add support for wineasio in winehq-staging, which has built-in realtime capabilities, soon? Thanks, Sam

**Comment by falkTX** [comment]
I am reworking the kx repos, wine and general applications are no longer supported 
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
