### ISSUE TITLE
package request: webcamoid update

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#107]
not priority, and maybe there's other tools too, but [Webcamoid](https://github.com/webcamoid/webcamoid) just added Jack support (I think, they closed my ticket for that saying alternative audio options now supported). So, could be a nice tool to have in KXStudio as long as it's this latest version or newer.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
