### ISSUE TITLE
package request: Tux Guitar 1.5

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#108]
Now ported to QT!

I tried the .deb they offer right at Sourceforge, but it had dependency conflicts and couldn't be installed.

**Comment by wolftune** [comment]
It *is* their problem. That bug as I linked is a real bug, and they also screwed up the packaging by not having the package in the PATH correctly.

**Comment by Vthyarilops** [comment]
I noticed this as well KXStudio seems to have 1.3 in there repositories but it shows up as 2:1.3.1-1kxstudio1 as such it attempts to overwrite 1.5.1

**Comment by XzuRukneg** [comment]
Fresh installation of kxstudio 16.04 last week, I can't install tuxguitar from repo due to many dependencies issues.

**Comment by wolftune** [comment]
update: 1.5.2 is available, I installed the .deb from them and it worked fine (on KDE Neon 16.04), seems at first check to no longer have the KXStudio attempt to overwrite issue.

**Comment by falkTX** [comment]
Yeah, I fixed that part a few weeks ago. As users want a new tuxguitar, and upstream already provides deb files, seems better to not force a version.
In the future, I will only force version for things I intend to update quickly on request.

**Comment by XzuRukneg** [comment]
Sorry, I said wrong.  I've installed ubuntu18.04 (not 16.04)and add kx repo, as always, with meta packages.
All good but can't install tuxguitar with synaptic!  
Maybe I missed something, cause I don't understand why provide a uninstallable version? (I know there is workaround)

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For tuxguitar, I recommend to switch over to the new repos, remove the kxstudio package of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
