### ISSUE TITLE
[package request] Beast

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#114]
From the official repo:

"Beast is a digital synthesizer and music creation system. It has support for Linux Audio Plugins (LADSPA), multi-track editing, unlimited undo, real-time synthesis, MIDI and various free audio codecs. Bse is the Beast Sound Engine, a library providing the synthesis and audio functions used by Beast."

A new version recently came out.

- Screencast of the new version on YouTube: https://www.youtube.com/watch?v=d0oh6x5xkvY
- Release announcement on Gnome mailing list: https://mail.gnome.org/archives/beast/2017-June/msg00007.html
- Tarball download: https://dist.testbit.org/beast/beast-0.11.0.tar.xz
- amd64 deb download: https://dist.testbit.org/beast/deb/beast_0.11.0_amd64.deb
- changelog: https://github.com/tim-janik/beast/blob/0.11.0/NEWS
- repo: https://github.com/tim-janik/beast
- website: https://beast.testbit.org/

For some reason, I can install it but running it doesn't do anything (on KXStudio 14.04).

Having it available in the repos and work straight away would be amazing.

**Comment by stragu** [comment]
- 0.12.0 was released in August 2018: https://mail.gnome.org/archives/beast/2018-August/msg00044.html
- The release notes are here: https://beast.testbit.org/release-notes

It looks like 0.12.0 drops support for anything older than Ubuntu 16.04, which is bad news for people who want to stick to 14.04 (not sure how  long you want to support it?).

Good news is JACK support is being developed: https://github.com/tim-janik/beast/pull/31

I could install both versions 0.11.0 and 0.12.0 on 18.04 (from .deb on https://beast.testbit.org/pub/deb/ ) but couldn't get sound out of them...

**Comment by stragu** [comment]
Actually, the no sound issue is fixed in both versions by starting Beast with the following command:

```
beast -p alsa=pulse
```

This solution comes from the issue I posted on the Beast project: https://github.com/tim-janik/beast/issues/80

**Comment by falkTX** [comment]
last time I tried to package beast, it was quite a pain.
I am giving up on it.

**Comment by tim-janik** [comment]
> last time I tried to package beast, it was quite a pain.
> I am giving up on it.

Hey @falkTX, could you please elaborate what issues you ran into when trying to package Beast, ideally on beast@gnome.org, so I can try to reproduce your issues?
A lot is changing at the moment regarding dependencies and how the UI is run and we are actively working on keeping AppImage builds working, which means it should run on most other dists out there.
Did you try to wrap it up as a .deb or something else? We intend to create a largish .deb package from the Beast installation tree in the future that could go under /opt/, similar to Google-Chrome, Bitwig or Atom, will that help?
