### ISSUE TITLE
Apt error Debian Unstable

### ISSUE THREAD

**Issue by alepeccioli** [KXStudio/Repository#115]
A warning appeared this week in Debian Unstable after an apt update:

W: Skipping acquire of configured file 'non-free/i18n/Translation-pt_BR' as repository 'http://kxstudio.linuxaudio.org/repo gcc5 InRelease' doesn't have the component 'non-free' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'non-free/i18n/Translation-pt' as repository 'http://kxstudio.linuxaudio.org/repo gcc5 InRelease' doesn't have the component 'non-free' (component misspelt in sources.list?)

Thanks!

**Comment by falkTX** [comment]
The non-free stuff does exist, but it's empty.
Should be ok to remove it from the list if you feel like it.
But since it's debian unstable, I don't if this is a bug on their side or how it's going to be defined later on...

**Comment by alepeccioli** [comment]
Thanks for the quick feedback Felipe! I'll check my sources list here.
