### ISSUE TITLE
Package request: FF Multi Converter

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#12]
winff is dead, we need some tool to convert videos.
handbrake is good but afaik it relies on build-time features instead of run-time. Might be tricky for generic builds.
FF Multi Converter was suggested, which seems to be a "simple" pyqt app. So it's likely to be simpler to package.

**Comment by wolftune** [comment]
I agree it looks promising. A GUI front-end to ffmpeg is clearly the preferable option. I would certainly appreciate it. Would be ideal if it were ported to qt5 though, on that: https://github.com/Ilias95/FF-Multi-Converter/issues/45

**Comment by wolftune** [comment]
that qt5 port of FF Multi Converter seems to be done now…

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
