### ISSUE TITLE
Update linuxsampler-*

### ISSUE THREAD

**Issue by FrnchFrgg** [KXStudio/Repository#120]
Since SVN 2855, the SFZ parser/player improved a lot with bug fixes and several key instructions now supported (<global> and <master> in particular, coming from ARIA and widely used in existing SFZ libraries).

Could LS be updated to newer versions ? (Carla would probably also benefit from it, since Travis pulls linuxsampler-static)

Thanks

**Comment by falkTX** [comment]
linuxsampler is updated now.
carla will get an updated version on the next rebuild, whenever that happens.

**Comment by falkTX** [comment]
linuxsampler is updated now.
carla will get an updated version on the next rebuild, whenever that happens.
