### ISSUE TITLE
[Package request] Aqualung

### ISSUE THREAD

**Issue by ghost** [KXStudio/Repository#121]
Hi!

I was previously using Audacious as a music player but it was a mess managing its jack connections. I went crawling the web and testing other players and found [Aqualung](http://aqualung.jeremyevans.net/), an audiophile oriented music player.

Quite feature packed and well documented, it compiled like a charm. Might be a nice alternative for intermediate/advanced users in a Jack aware environment.

Cheers,
Barbouze

**Comment by falkTX** [comment]
Audacious latest releases have been working nicely for me.
the webupd8 PPA has the latest version of it in its repositories.

Aqualung is related to music, but it's not something one uses to produce music afaik...
There's likely a PPA with updates to it already.

**Comment by Barbouze** [comment]
No problem, I was just so pleased with it that I forgot that "it's not something one uses to produce music afaik..." and you"re right to remember this to me :+1: 
Keep up the good work and sorry for the noise!

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
