### ISSUE TITLE
Audacity and calf-plugins-git plugins don't like each other

### ISSUE THREAD

**Issue by DanielKonopka** [KXStudio/Repository#122]
Hello,

Could somebody please confirm that calf-plugins-git (LV2) do not work with Audacity 2.1.2?

In order for it to work, a chunk like this:

```
    ] , [
        a lv2:InputPort ;
        a atom:AtomPort ;
        lv2:index 20 ;
        lv2:symbol "events_in" ;
        lv2:name "Events" ;
        lv2:portProperty lv2:connectionOptional ;
        atom:bufferType atom:Sequence ;
        atom:supports lv2midi:MidiEvent ;
        atom:supports atom:Property ;

    ] , [
        a lv2:OutputPort ;
        a atom:AtomPort ;
        lv2:index 21 ;
        lv2:symbol "events_out" ;
        lv2:name "Events" ;
        lv2:portProperty lv2:connectionOptional ;
        atom:bufferType atom:Sequence ;
        atom:supports lv2midi:MidiEvent ;
        atom:supports atom:Property ;

    ]
```

has to be removed from a .ttl file for the plugin in question (ie. /usr/lib/lv2/calf.lv2/Compressor.ttl) but then Calf plugins do not work in Ardour (crash upon load). Looks like it has something to do with MIDI.

**Comment by falkTX** [comment]
I guess audacity does not like plugins with event ports. probably an incomplete LV2 implementation.
Ardour crash is because you basically removed stuff from the plugin, which breaks it. Don't do that.

**Comment by DanielKonopka** [comment]
What am I supposed to do now? Report to Audacity team?

**Comment by falkTX** [comment]
hmm yes :)
(just 2 years late)
