### ISSUE TITLE
latest version of Ingen

### ISSUE THREAD

**Issue by tjingboem** [KXStudio/Repository#123]
the latest updated version of Ingen. 
Recently a long standing bug was solved: Fix saving of learned MIDI bindings, an important update!

(update the "gcc5" version is probably needed)

**Comment by falkTX** [comment]
this was already done some weeks ago, forgot to close this issue.
if you need yet another update, please let me know.
but there are deep lv2 libs changes incoming, so better wait a bit and then update all lv2 stuff at once.
