### ISSUE TITLE
[package request] VCVRack

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#124]
Not sure if that is possible to add to the repos, but thought it looked interesting:

> Rack is the engine for the VCV open-source virtual Eurorack DAW.

> VCV Rack is the engine powering VCV modules. Add modules, connect cables, edit parameters, and save/load patches. Create generative patches with your mouse, perform with your MIDI keyboard controller, or connect it to your favorite DAW using the Rack Bridge VST/AU plugin (coming soon). In Rack, control voltages and audio signals are equivalent, so you can modulate parameters with sonic-range VCOs to create customizable FM synths or chaotic wave-shaping oscillators. If you already own a modular synthesizer, you can enhance your setup with an audio interface supporting CV signals or a CV-MIDI-CV interface module with Rack's CV Interface (coming soon).

- source: https://github.com/VCVRack/Rack
- website: https://vcvrack.com/

**Comment by falkTX** [comment]
This is already packaged, but not in the best way (need static libs so it's installable everywhere).
Right now it only installs on Ubuntu 14.04

**Comment by falkTX** [comment]
vcvrack on kxstudio is now version 0.5.1

**Comment by robbbreckenridge** [comment]
I'm grabbing 3rd party plugins and dropping the folders with the .so files in /usr/lib/vcvrack/plugins but they're not showing up. Perms and ownership match the existing built-ins. 

Any magic to get the others working?

**Comment by falkTX** [comment]
You can't grab 3rd party plugins like that, the C++ ABI is not stable, and thus the binaries don't work.
You'll have to use the same compiler (more or less) that is used to build those plugins in order to make them work - ie, use the upstream VCVRack linux binary.
I will make a vcvrack-plugins package to avoid this issue.

**Comment by robbbreckenridge** [comment]
ah, gotcha. thanks.
