### ISSUE TITLE
Package request: Minuet

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#13]
http://sandroandrade.org/a-minuet-for-kde/ looks neat and I'd like to try it and potentially recommend it. Seems it would be easiest if it were packaged in KXStudio for everyone.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
