### ISSUE TITLE
linuxsampler volume in carla

### ISSUE THREAD

**Issue by varpa** [KXStudio/Repository#131]
When a sample is loaded directly in linuxsampler using qsampler there is a global volume adjustment possible which I always set to 100%, though the default is something like 35% which is much quieter.  When a sample is loaded in carla (which invokes linuxsampler internally, I believe) there is no way to control the linuxsampler volume adjustment which seems to end up at the default of 35% which is not very loud.   The carla volume adjustment does not raise the volume very much so samples played with carla need an extra amplification to be loud enough.  My request is that the carla adjust the linuxsampler volume to 100% so the sample is loud enough (or provide a way to adjust the internal linuxsampler volume).   The carla volume control can then be used to lower the volume if needed.

**Comment by falkTX** [comment]
hmm old ticket, closing, sorry.
carla no longer uses linuxsampler
