### ISSUE TITLE
Make pulseaudio-modules-jack installed by default?

### ISSUE THREAD

**Issue by unfa** [KXStudio/Repository#133]
Hey! One problem I have is that I have to install the JACK module for PulseAudio every time, to have Cadence's JACK-PA bridge working. Maybe it'd be good to have that as a dependancy for Cadence? IDK, it'd be great to have it already there after installing a bunch of KX Studio meta-packages.

I know it's not needed if one doens't use PA at all, but is there a way to have that JACK module installed IF cadence and PA are present in the system? Maybe ask the use if he wants to install this Cadence during installation?

What do you think? That could remove one extra step needed to get a production-ready studio system I guess.

**Comment by falkTX** [comment]
Problem with this is that, if we depend on pulseaudio-module-jack, pulseaudio will get installed as well - even for those people who do not have it installed yet.
I patch the ubuntu packages when using the kxstudio repos to bring in pulseaudio-module-jack (as recommends), but doesn't always work.

I think instead that cadence should display an error if this module is not installed.

**Comment by unfa** [comment]
That might be a good idea. A lot of problems arise when PA and JACK are not playing well together, a message asking to install PA JACK module if that would be beneficial could be a headache saver for many novice users.

**Comment by falkTX** [comment]
This cannot be done with generic purpose packages.
I made pulseaudio-module-jack a dependency of cadence, that will be it
