### ISSUE TITLE
how do i install on artful

### ISSUE THREAD

**Issue by bertff01** [KXStudio/Repository#135]
I'm trying to install on artful there is no package names kxstudio-meta-audio anymore someone in a irc help room said they changed the name of package and I should ask the devs.

**Comment by falkTX** [comment]
The instructions are on http://kxstudio.linuxaudio.org/Repositories
They apply to all versions.

Perhaps you're missing a `sudo apt-get update` ?

**Comment by bertff01** [comment]
yes did the apt-get update
this is my output from that command
https://pastebin.com/mE8x8RTg
when i run apt-get install kxstudio-meta-audio* 
it can't find it or any package by kxstudio other than the repositories I installed
http://paste.ubuntu.com/25809529/
not really sure what could be wrong I upgraded from 17.04 to 17.10

**Comment by falkTX** [comment]
I'm closing this bug as there is nothing more to do on it.
