### ISSUE TITLE
[Package Update] GxTuner

### ISSUE THREAD

**Issue by Allfifthstuning** [KXStudio/Repository#138]
I would love to see GxTuner updated.
https://github.com/brummer10/gxtuner

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

**Comment by wolftune** [comment]
isn't gxtuner a plugin?

**Comment by falkTX** [comment]
There is a plugin that is part of guitarix, and that gxtuner repo which provides a jack standalone version of it.

a very good alternative is "tuna", part of x42-plugins.

**Comment by wolftune** [comment]
so the new plugin-focused repos *will* include the plugin parts of the project, including the plugin version of gxtuner though?

Incidentally, tuna seems great, but it doesn't support the microtonal options that gxtuner has (though I'd love if it did, I opened https://github.com/x42/tuna.lv2/issues/4 )

**Comment by falkTX** [comment]
I do not think I can update guitarix plugins without packaging guitarix too, which is unfortunate.
I understand wanting some specific features, but I also have to be real and not overstretch too much again.
The old repos had packages that got quite outdated, will not repeat that now, but it involves sacrificing other things
