### ISSUE TITLE
Package request: Sequencer64

### ISSUE THREAD

**Issue by korakios** [KXStudio/Repository#14]
Seq24 is updating!

https://github.com/ahlstromcj/sequencer64

Maybe we could try it in KXstudio?

**Comment by chaocrator** [comment]
bump.
sequencer64 has regular releases now, and all debian packaging stuff in repo & source tarball.
it even had some deb packages, even made for kxstudio, but irregularly.
and it's far more usable now, than its predecessor seq24.

**Comment by chaocrator** [comment]
well, for those who interested:
at the moment, it's really easy to build a .deb package locally, but i could not manage to make it buildable non-interactively, so can't put it to ppa.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
