### ISSUE TITLE
package request: Audacity 2.2

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#141]
This is huge for having a dark theme finally. Also, MIDI support. And more

**Comment by chaocrator** [comment]
just FYI:
there's a PPA, and it works.
https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/audacity

**Comment by wolftune** [comment]
@chaocrator thanks, that worked!

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
