### ISSUE TITLE
gigedit seems broken in KXStudio

### ISSUE THREAD

**Issue by CG-3D** [KXStudio/Repository#142]
I tried using gigedit with LinuxSampler (both from the KXStudio repo) but I cannot get them to work.
On startup, LinuxSampler reports 'undefined symbol: _ZN12LinuxSampler6Thread10DestructorEv'...

I have tried it on Linux Mint 18.2, Ubuntu 17.10, Ubuntu Studio 17.04, Debian 9 KDE and even Debian 8.5 Jessie KDE.
On all but the latter I have installed the GCC5-repo as well.

The only combination that worked was Debian Jessie 8.5 KDE with the (old) binaries provided by linuxsampler.org.

Is gigedit supposed to work with linuxsampler in KXStudio or are they obsolete?

Thanks and greetings,
CG3D

**Comment by m4l3z** [comment]
Hey,
Reproduced on Linux Mint 18.1

**Comment by falkTX** [comment]
I updated linuxsampler yesterday.
Please get all the updates and check if this is still an issue or not.

**Comment by CG-3D** [comment]
I have tried the new Linuxsampler and gigedit on Linux Mint 18.2 and can confirm that the issue is solved. Live editing with gigedit now works fine if Linuxsampler is running standalone.

I still cannot run gigedit from within QSampler when Linuxsampler is running as a (LV2) plugin in Ardour or Carla, but I think that is a different issue than this one. This one seems fixed.

 Thank you very much falkTX!

**Comment by m4l3z** [comment]
Works fine in standalone ! Thanks @falkTX 
I got the same issue as @CG-3D as an LV2 plugin.
