### ISSUE TITLE
Carla - Win VST

### ISSUE THREAD

**Issue by luciorgomes** [KXStudio/Repository#145]
The last version of Carla don't load the UI from Win VST plugins. Here's the log of an example:

Loading  /home/lucio/.wine/drive_c/Program Files/VstPlugIns/Voxengo/Boogex.dll
fixme:heap:RtlSetHeapInformation 0x240000 0 0x23f3e0 4 stub
err:clipboard:convert_selection Timed out waiting for SelectionNotify event
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  95
  Current serial number in output stream:  98

**Comment by falkTX** [comment]
Is this with a single plugin, or all of them?
(from different manufacturers)

**Comment by luciorgomes** [comment]
All plugins...

Loading  /home/lucio/.vst/Crystal/Crystal.dll
fixme:heap:RtlSetHeapInformation 0x240000 0 0x23f3e0 4 stub
err:clipboard:convert_selection Timed out waiting for SelectionNotify event
err:clipboard:convert_selection Timed out waiting for SelectionNotify event
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x4200001
  Serial number of failed request:  79
  Current serial number in output stream:  79

Loading  /home/lucio/.vst/TDR Nova/VST2/Win32/TDR Nova.dll
err:clipboard:convert_selection Timed out waiting for SelectionNotify event
err:clipboard:convert_selection Timed out waiting for SelectionNotify event
fixme:ver:GetCurrentPackageId (0x84e9d8 (nil)): stub
fixme:win:RegisterTouchWindow (0x10056 00000000): stub
fixme:msg:ChangeWindowMessageFilterEx 0x10056 233 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 4a 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 49 1 (nil)
fixme:win:RegisterTouchWindow (0x10058 00000000): stub
fixme:msg:ChangeWindowMessageFilterEx 0x10058 233 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10058 4a 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10058 49 1 (nil)
fixme:wgl:ConvertAttribWGLtoGLX unsupported 201e WGL Attribute
fixme:wgl:ConvertAttribWGLtoGLX unsupported 201f WGL Attribute
fixme:wgl:ConvertAttribWGLtoGLX unsupported 2020 WGL Attribute
fixme:wgl:ConvertAttribWGLtoGLX unsupported 2021 WGL Attribute
fixme:win:RegisterTouchWindow (0x20058 00000000): stub
fixme:msg:ChangeWindowMessageFilterEx 0x20058 233 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x20058 4a 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x20058 49 1 (nil)
fixme:x11drv:X11DRV_DestroyNotify window 0x20040/4200003 destroyed from the outside

Loading  /home/lucio/.wine/drive_c/Program Files (x86)/VstPlugins/Kontakt/64/Kontakt 5.dll
fixme:win:RegisterDeviceNotificationW (hwnd=0x10050, filter=0x23f690,flags=0x00000004) returns a fake device notification handle!
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d4800 (device=2d access=1 func=200 method=0)
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:ntdll:EtwRegisterTraceGuidsW (0x30ec34, (nil), {f7b697a3-4db5-4d3b-be71-c4d284e6592f}, 7, 0x3cebb0, (null), (null), 0x3d2280): stub
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
fixme:process:GetNumaHighestNodeNumber (0x23f0e0): semi-stub
fixme:ver:GetCurrentPackageId (0x94e550 (nil)): stub
fixme:heap:RtlSetHeapInformation 0x1880000 0 0x23f140 4 stub
fixme:heap:RtlSetHeapInformation 0x4250000 0 0x23f0c0 4 stub
fixme:x11drv:X11DRV_DestroyNotify window 0x1007a/3c00003 destroyed from the outside
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(0)
fixme:shell:IDropTargetHelper_fnShow (0x85a09a0)->(1)
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4160416, 0000: semi-stub!

**Comment by falkTX** [comment]
Are these all 64bit plugins? Is there a 32bit plugin you can try?

**Comment by luciorgomes** [comment]
This are 32 and 64 bit of the same plugins. Same results....

======= Starting engine =======
======= Engine started ========
Error opening file /home/lucio/.lv2/Synthpod_default.preset.lv2/manifest.ttl (Arquivo ou diretório não encontrado)
lilv_world_load_file(): error: Error loading file `file:///home/lucio/.lv2/Synthpod_default.preset.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/lucio/.lv2/Synthpod_default.preset.lv2/manifest.ttl
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2006 Chris Cannam
**Loading  /home/lucio/.vst/TSE/BODv2_x64.dll**
fixme:win:RegisterTouchWindow (0x10056 00000000): stub
fixme:msg:ChangeWindowMessageFilterEx 0x10056 233 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 4a 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 49 1 (nil)
fixme:ver:GetCurrentPackageId (0x13ae550 (nil)): stub
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x4c00003
  Serial number of failed request:  97
  Current serial number in output stream:  100
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2006 Chris Cannam
**Loading  /home/lucio/.vst/TSE/BODv2_x86.dll**
fixme:win:RegisterTouchWindow (0x10056 00000000): stub
fixme:msg:ChangeWindowMessageFilterEx 0x10056 233 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 4a 1 (nil)
fixme:msg:ChangeWindowMessageFilterEx 0x10056 49 1 (nil)
fixme:ver:GetCurrentPackageId (0x128e9d8 (nil)): stub
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x4c00003
  Serial number of failed request:  97
  Current serial number in output stream:  100

**Comment by falkTX** [comment]
oh this is actually using dssi-vst, not carla's implementation.
no wonder that doesn't work.

Did you enable experimental options in carla settings yet? (this is now required after the latest update)
You also need to enable bridges + wine bridges on the experimental tab.

**Comment by luciorgomes** [comment]
Ok, I got it, thanks!!!

**Comment by falkTX** [comment]
So it's working for you again now?

**Comment by luciorgomes** [comment]
Yes!

**Comment by falkTX** [comment]
Good to know :)
Closing the bug then.
