### ISSUE TITLE
Carla-git last update can not find windows vst

### ISSUE THREAD

**Issue by Shupacabras** [KXStudio/Repository#146]
Hi
carla-git 2:1.9.7+git20171111 amd64 Ubuntu 17.10
![captura de pantalla_2017-11-20_13-48-17](https://user-images.githubusercontent.com/6946626/33030246-9a0c0d82-cdf9-11e7-9fdb-50beb903685a.png)

Kontakt and Korg M1 work correctly before updating yesterday
Rescanning does not add them to the list

updated list
carla-bridge-win32 (2:1.9.7+git20170821.3) to 2:1.9.7+git20171118.2
carla-bridge-win64 (2:1.9.7+git20170821.3) to 2:1.9.7+git20171118.2
carla-bridge-wine32:i386 (2:1.9.7+git20170107.2) to 2:1.9.7+git20171118
carla-data (2:1.9.7+git20170828v5) to 2:1.9.7+git20171118.2
carla-git (2:1.9.7+git20170828v5) to 2:1.9.7+git20171118.2
carla-lv2 (2:1.9.7+git20170828v5) to 2:1.9.7+git20171118.2
carla-plugins-lv2 (2:1.9.7+git20170828v5) to 2:1.9.7+git20171118.2

sorry my bad english
Regards

**Comment by falkTX** [comment]
You need to enable experimental stuff in settings, then plugin bridges, then wine bridges too.

**Comment by Shupacabras** [comment]
Thank you
is work, Regards
