### ISSUE TITLE
Carla lost it's bridges

### ISSUE THREAD

**Issue by eighthkeepa** [KXStudio/Repository#147]
Hello. 

Sorry if that issue was already discussed here, but I have to ask about it. 

First of all - I'm using Debian Stable and I have three versions of Carla in connected repos. 
First one is Carla 1.2.4 from kxstudio repo for Lucid. 
The second one is Carla-git (1.2.7) for trusty
The third one is Carla-git (1.2.7) for xenial. 

And I got some problems with all of them. 
Well, I can describe it as the topic name is - Carla loses all discovery tools except native discovery. 
I have installed wine-rt and wine-rt-amd64 and I had made Carla work with win64 VSTs only after 10th or 20th attempt. However, it only works with Carla-single. It seems that Carla-single can load every 64bit plugin I have. 
Unfortunately, Carla itself can't do that. Because there is no even option for it. It just can't see Carla-discovery-win64 and Carla-discovery-win32. 
It seems like Carla 1.2.4 can see a win32-discovery tool, but that's it. 
Other versions just won't use any discovery tools but native plugin discovery.  

So, the question is - what should I do with it? 
I also tried Debian's default wine, but it can't even work with Carla-single - it just won't launch. 

Sorry for bad english.

**Comment by falkTX** [comment]
See #146

**Comment by eighthkeepa** [comment]
Thanks!

вс, 26 нояб. 2017 г. в 19:16, Filipe Coelho <notifications@github.com>:
