### ISSUE TITLE
Severe Dependency Issue Question while installing carla-bridge-win*

### ISSUE THREAD

**Issue by johannesmenzel** [KXStudio/Repository#148]
After, with some grumble, switching the home studio back to Windows, because of many beloved Plugins I just realized that the solution was already there. So I just tried to install carla-git (which worked) and afterwards carla-bridge-win*, which resulted in this:

```
sudo apt-get install carla-bridge-wine64 carla-bridge-win64 
[...]
Die folgenden Pakete werden ENTFERNT:
  a2jmidid audacity blender csound csound-utils devede espeak fluidsynth fluidsynth-dssi gem gem-extra gem-plugin-gmerlin gem-plugin-lqt gem-plugin-magick gem-plugin-v4l2 gmidimonitor gstreamer1.0-plugins-bad guitarix-ladspa
  hydrogen jack-capture jackd2 jackd2-firewire jamin jconvolver kdenlive laditools libcsound64-6.0 libespeak1 libflext-pd0 libfluidsynth1 libjack-jackd2-0 libjack-jackd2-dev libmlt++3 libmlt6 libportaudio2 libsynfig0v5 lmms
  melt mencoder meterbridge mod-ui mplayer musescore openshot pd-3dp pd-ambix pd-arraysize pd-aubio pd-autopreset pd-bassemu pd-beatpipe pd-boids pd-bsaylor pd-chaos pd-cmos pd-comport pd-creb pd-csound pd-cxc pd-cyclone
  pd-earplug pd-ekext pd-ext13 pd-extendedview pd-fftease pd-flext-dev pd-flite pd-freeverb pd-ggee pd-gil pd-hcs pd-hexloader pd-hid pd-iem pd-iemambi pd-iemguts pd-iemlib pd-iemmatrix pd-iemnet pd-iemutils pd-jmmmp
  pd-kollabs pd-libdir pd-list-abs pd-log pd-lua pd-lyonpotpourri pd-mapping pd-markex pd-maxlib pd-mediasettings pd-mjlib pd-moonlib pd-motex pd-mrpeach pd-mrpeach-net pd-nusmuk pd-osc pd-pan pd-pddp pd-pdogg pd-pdp
  pd-pdstring pd-pduino pd-plugin pd-pmpd pd-puremapping pd-purepd pd-purest-json pd-readanysf pd-rtclib pd-scaf pd-sigpack pd-slip pd-smlib pd-syslog pd-tclpd pd-testtools pd-unauthorized pd-upp pd-vbap pd-wiimote
  pd-windowing pd-xbee pd-zexy petri-foo pitivi pulseaudio-module-jack puredata puredata-core puredata-extra puredata-import python-laditools python-mlt qmidinet qsynth synfigstudio vlc-plugin-fluidsynth vlc-plugin-jack
  yoshimi zita-at1 zita-lrx zita-mu1 zita-rev1
Die folgenden NEUEN Pakete werden installiert:
[...]
0 aktualisiert, 168 neu installiert, 144 zu entfernen und 0 nicht aktualisiert.
Es müssen 127 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 453 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] n
```

I shortened it a little, because the main question is, why it wants to delete all that packages. For me it looks like a conflicting meta package from UbuntuStudio, but what is the actual Problem here?

Often enough I just made things worse by just try-n-erroring around. May be capable to do it and reinstall the packages again, but may be lead into trouble as well.

**Comment by falkTX** [comment]
It's impossible to know with just this.
Likely an issue with wine or 32bit libraries.
See if you can install wine-rt first, or wine-staging if you prefer.

**Comment by johannesmenzel** [comment]
That was incredibly fast. Managed now to install that. i asked because these plugins to remove were packages from ubuntustudio-audio and ubuntustudio-audio-plugins meta package. Wondered if that is somehow conflicting with kxstudio repos.

Was able to add Win-VST plugins to Carla, but not to load them by now because of memory allocation error. Maybe I shoundn't have load them all at once...

**Comment by falkTX** [comment]
The memory allocation thing is because you're not in the audio group yet.
Just do:
```
sudo addgroup $(whoamI) audio
```
Then reboot or re-login.

The thing about the ubuntustudio packages is likely related to *-git packages, like calf-plugins-git or zynaddsubfx-git, which they don't support.
Anyway, happy to know it was just a minor thing. :)

**Comment by johannesmenzel** [comment]
```
$ sudo addgroup hannes audio
[sudo] Passwort für hannes: 
Der Benutzer »hannes« ist bereits ein Mitglied der Gruppe »audio«.
```

By $(whoamI) I guess you mean to add my user name to the audio group? Well, since I'm using the Linux Audio thing quite a while, I am already in audio group, so I'm afraid, that memory thing should be related to another issue.

**Comment by falkTX** [comment]
hmm then sure it's a different issue.
post here the entire error or a screenshot, and I will take a look.

**Comment by johannesmenzel** [comment]
```
$ carla
QApplication: invalid style override passed, ignoring it.
Using "fusion" theme
Carla 1.9.7 (2.0-beta5) started, status:
  Python version: 3.6.3
  Qt version:     5.9.1
  PyQt version:   5.7
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libjack.so.0 loaded sucessfully!
[MOMENT WHEN VST LOADING]
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

Can you tell me, which log is most suitable to look for

/var/log/apport.log looks not that helpful

```
ERROR: apport (pid 15650) Wed Nov 29 14:41:22 2017: debug: session gdbus call: 
ERROR: apport (pid 15650) Wed Nov 29 14:41:22 2017: this executable already crashed 2 times, ignoring
ERROR: apport (pid 16055) Wed Nov 29 14:47:07 2017: called for pid 15980, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 16055) Wed Nov 29 14:47:07 2017: script: /usr/share/carla/carla, interpreted by /usr/bin/python3.6 (command line "/usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr")
ERROR: apport (pid 16055) Wed Nov 29 14:47:07 2017: gdbus call error: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
```

/var/crash/_usr_share_carla_carla.1000.crash is a text file of incredible 16 MB, don't know, where to start.

Cannot do a screenshot, cause Carla is closing immediately after trying to load the VST.

**Comment by falkTX** [comment]
Does it happen with all plugins, or a single one?

Disable the capture of logs on the carla's settings main tab, so everything will be on the terminal.
The fact that the Carla style can't be loaded (log right at the start) makes me think there's some weird setup or incompatibility going on.
Try to load the plugin using `carla-single` in the command line.

**Comment by johannesmenzel** [comment]
First I thought, it was on every plugin, but after some try I found out that for example Sonimus SonEQ is loading.

Here is the output for "TDR Kotelnikov", which lets carla crash:

```
carla
QApplication: invalid style override passed, ignoring it.
Using "fusion" theme
Carla 1.9.7 (2.0-beta5) started, status:
  Python version: 3.6.3
  Qt version:     5.9.1
  PyQt version:   5.7
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libjack.so.0 loaded sucessfully!
Using WINEPREFIX '/home/hannes/.wine'
starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win64.exe "VST2" "/mnt/daten/VST-Linux/Win-VST/TDR Kotelnikov.dll" "TDR Kotelnikov" 1415854390
QXcbConnection: XCB error: 3 (BadWindow), sequence: 749, resource id: 15151317, major code: 40 (TranslateCoords), minor code: 0
WINE realtime scheduling hack enabled, realtime base priority has been set to 15
wineserver running SCHED_NORMAL
Carla assertion failure: "jassertfalse triggered" in file files/File.cpp, line 158
Carla Bridge Ready!
Speicherzugriffsfehler (Speicherabzug geschrieben)

```

**Comment by johannesmenzel** [comment]
Oh, but with carla-single it was possible to load that plugin (or, the gui)

**Comment by falkTX** [comment]
I can reproduce the issue, carla crashes with this plugin.
Since it's running as a bridge, it should never be possible to crash carla... so carla is doing something it should not.
No error on your side, but mine. I will fix it soon and push an update to the repos.

**Comment by johannesmenzel** [comment]
I will do some further tests. By now I tried:

"Sonimus SonEQ" (Free): Works Properly
"Ignite Amps PTEq-X": Works with Host Rack GUI, but crashes on loading Plugin-GUI
"TDR Kotelnikov" and "TDR VOS SlickEQ": Crashes

**Comment by falkTX** [comment]
I found the issue, will push an update to the repos now.

**Comment by johannesmenzel** [comment]
Anyway, carla and everything else is a gourgous effort. Would be so happy to switch back to linux for audio as well

Many, many thanks!

**Comment by johannesmenzel** [comment]
The update didn't solve that for me. Anyway, like mentioned in the list above, 3 of the go-to plugins are already working. Makes hope for future use.

**Comment by falkTX** [comment]
You need to check again for the update which ends in ".2".
I already had an update pushed before you reported the issue.
