### ISSUE TITLE
Carla Blank Panels (feature request)

### ISSUE THREAD

**Issue by cmorse01** [KXStudio/Repository#149]
I like saving off various setups as Carla project files.  I was envisioning something whereby one could insert blank panels into the rack (blank as in no audio/control connections) that one could put labels on to - sort of the digital equivalent of a blank panel in a hardware rack to which one can slap a piece of gaffer tape with notes written in sharpie marker etc.

It could be useful to put a blank at the top of a rack with the song/setup name, and then insert additional panels below rack 'groups' with brief notes about which knobs are tied to which hardware controllers. (Did I put Filter Cutoff on Rotary 4 or Rotary 6?) 

Similar to the Notes module, but instead of a notepad type app, it would simply 'tape' a text label onto a blank in the rack.  And either a user selectable variable font size, or at least a larger fixed font size than the standard module labels so it can be easily seen without being right on top of the computer monitor.  A 4k monitor is really nice for spreading GUIs out, but reading the text can be challenging.

Seems like it might be fairly easy to implement, but I have no idea where to begin to write one myself.

**Comment by falkTX** [comment]
I appreciate the feature request, but this is really not the issue for carla things.
Please open the same issue on my carla github project instead, and we can have a discussion there.
Thank you.
