### ISSUE TITLE
Package request: Nootka update

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#150]
http://nootka.sourceforge.net already packaged but very outdated, has been totally redone with newer libraries etc. .deb already available to download so maybe easy to just include…

(At some point, the question is whether it's good to have really old stuff packaged versus nothing… clearly the newer would be ideal but is easy enough to install otherwise)

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
