### ISSUE TITLE
Installing Rosegarden 17.04 

### ISSUE THREAD

**Issue by jaddytucson** [KXStudio/Repository#152]
Hello,

I took the undertaking of learning Linux by installing Rosegarden, which has been a very steep learning curve. It involved installing a dssi header, with the right environment labels and I continue to follow instructions in the readme, after extracting Rosegarden. I have an older version still installed but try to extract the newer version with each new "make" attempt. I think my trouble is with Cmake. Please let me know if there is a way to find the required package or fix this issue somehow (below): 

$ cmake .. -DCMAKE_INSTALL_PREFIX=[PREFIX] (this is the command i type in, as is...)

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Autodetecting Qt version to use
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.7", minimum required is "4.8.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'alsa>=0.9'
--   Found alsa, version 1.1.4.1
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Checking for module 'liblo>=0.7'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:156 (pkg_check_modules)

Also note the paragraph above- I find "A required package was not found," to be a bit creepy. Thank you and I hope to hear from someone soon!

**Comment by jaddytucson** [comment]
i have solved this issue on my own and would explain, for anyone interested- that not having liblo installed was certainly the answer. looking at "liblo>=0.7" before the error message was the answer. however, i also found a solution in using apt-get build-dep <rosegarden>, which is a much more efficient way of continuing to load modules and dependencies-- as the process can be long and tedious. thank you but this issue is no longer a problem for me.

**Comment by a13** [comment]
why didn't you use a prebuilt package?

**Comment by jaddytucson** [comment]
i could not find one for the latest version! at the time i began, things were still very new to me. i guess i'll just leave this thread open... you know i actually switched to linux for this application. using soundfonts is awesome. happy holidays!

**Comment by falkTX** [comment]
now updated to 17.12
