### ISSUE TITLE
[Package request] Simple Screen Recorder

### ISSUE THREAD

**Issue by Allfifthstuning** [KXStudio/Repository#153]
http://www.maartenbaert.be/simplescreenrecorder/

Thanks in advance!

Hans

**Comment by ericfont** [comment]
I can't speak for the main devs, but I think KXStudio should only focus on Audio applicantions so the base distro doesn't get bloated and so don't get distracted with supporting every pacakge someone likes.

Anyway, Simple Screen Recorder is already just an apt-get install away on Debian KXStudio and via PPA on ubuntu:
Debian: https://packages.debian.org/sid/simplescreenrecorder
Ubuntu: https://launchpad.net/~maarten-baert/+archive/ubuntu/simplescreenrecorder

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
