### ISSUE TITLE
missing qtractor.desktop files 

### ISSUE THREAD

**Issue by rghvdberg** [KXStudio/Repository#155]
There's no menu entry for Qtractor.
Have this problem on several installs.

**Comment by falkTX** [comment]
I know. Upstream removed the desktop files from source.
Likely I am missing something...

**Comment by rncbc** [comment]
.desktop files are upstream alright as ever been cf. [qtractor.desktop](https://github.com/rncbc/qtractor/blob/master/src/qtractor.desktop)

byee

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
qtractor will not be in the new repos
