### ISSUE TITLE
Carla as plugin on Ardour - libpng16-16

### ISSUE THREAD

**Issue by luciorgomes** [KXStudio/Repository#158]
Carla plugin GUI was not loading in Ardour (there was just a black canvas on the plugin window). On the linux terminal I've got the error messages above. 

After the install of the libpng16-16 the plugin was shown as expected on the DAW. 

I believe that this lib must be selected as a dependency for Carla on install.

-------------------------------------------------------------------------------------------------------------------------------
Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin-patchbay"
LRDF Support not available (LADSPA-RDF will be disabled)

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado

(python3:12048): Gtk-WARNING **: libpng16.so.16: Não é possivel abrir arquivo de objetos compartilhado: Arquivo ou diretório não encontrado
Carla 1.9.8 (2.0-beta6) started, status:
  Python version: 3.5.2
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
CarlaPipeCommon::_writeMsgBuffer(..., 10) - failed with -1 (true), message was:
transport

**Comment by falkTX** [comment]
This has nothing to do with carla itself..
Carla does not use Gtk, ardour does.

You might need to rebuild carla, ardour, or both.

**Comment by luciorgomes** [comment]
I'm using the Kx Studio repositories. Ardour and Carla came from it.

**Comment by falkTX** [comment]
Carla itself does not rely on libpng at all, so this will be an issue somewhere else.
Maybe in python package, or Qt, or PyQt. but in any case it comes from something that is not handled by kxstudio directly.
FIxing this would involve fixing a shared library package, which is not possible for such generic repos like kxstudio. So there is nothing I can do from my side to have this fixed.
It's likely to be specific to a single distro version too.
