### ISSUE TITLE
Package request: update Sonic Visualiser

### ISSUE THREAD

**Issue by rghvdberg** [KXStudio/Repository#16]
https://code.soundsoftware.ac.uk/projects/sonic-visualiser/files

**Comment by wolftune** [comment]
New v3 is out, major update! Easy deb available for Ubuntu 16.04+ already, but it would be *nice* to include the package in KXStudio

**Comment by wolftune** [comment]
Hmm, actually there's this issue that arises when just installing v3:

```
Failed to load plugins
Failed to load one or more plugin libraries:
/usr/lib/ladspa/dssi-vst.so
Library contains no plugins
/usr/lib/dssi/dssi-vst.so
Library contains no plugins
These plugins may be incompatible with the system, and will be ignored during this run of Sonic Visualiser.
```

**Comment by falkTX** [comment]
dssi-vst requires VST_PATH env var to be set in order to be usable.
I'm not sure you need it for yourself though (do you want to run windows plugins?).

**Comment by rghvdberg** [comment]
Totally forgot I filed this issue :)

V3 from Sonic Visualiser website gave lots of trouble. I went back to v2

Worth troubleshooting though because it's a great app.

**Comment by wolftune** [comment]
I am potentially interested in being able to use Windows VSTs in general, but not in Sonic Visualizer particularly. It probably makes sense to report to them that the Linux build shouldn't bring up that error.

@rghvdberg can you clarify what trouble you had?

FWIW, I've had no other issues myself

**Comment by rghvdberg** [comment]
Will test and report

**Comment by rghvdberg** [comment]
Installed version 3 on kubuntu 17.04. Added qm plugins.
No issue so far.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
