### ISSUE TITLE
New x42 vsts showing up as effects rather than instruments

### ISSUE THREAD

**Issue by spectromas** [KXStudio/Repository#162]
Just got around to trying the new VSTs converted from lv2 and I noticed that the x42 instruments (drum kits and organ) are showing as effects in the latest Renoise.

**Comment by falkTX** [comment]
I know, it's because they have midi output ports and the lv2vst code is not very smart regarding this.
I have an idea on how to handle it better.

**Comment by falkTX** [comment]
I believe it is fixed now, if not please reopen.
I know I did a fix for this, but dont recall if it was enough or not..
