### ISSUE TITLE
[package suggestion] sonic-pi

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#164]
Live coding music synth, with a focus on teaching.
Sounds very interesting, had never come across it until today.

- ppa: https://launchpad.net/~sonic-pi/+archive/ubuntu/ppa
- repo: https://github.com/samaaron/sonic-pi
- website: http://sonic-pi.net/

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

**Comment by stragu** [comment]
Great to know, thank you for the info, @falkTX ! All the best with this new KXStudio chapter, and as always: thank you for your generous work! :)
