### ISSUE TITLE
package request: airwindows native VSTs

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#167]
https://github.com/airwindows/airwindows/tree/master/plugins/LinuxVST seems super easy to package actually. Binaries are even available already at http://www.airwindows.com/airwindows-linux/ but have to be annoyingly extracted from zips that have MacOS and Windows files as well as the Linux .so files. Would be nice to just be packaged cleanly in KXStudio.

**Comment by x7i7l** [comment]
I second that!

**Comment by franlopez** [comment]
Third that!

**Comment by falkTX** [comment]
They are in the repos now as "airwindows" package.
Whenever an update is needed, let me know.
