### ISSUE TITLE
Package request: vcvrack-plugins

### ISSUE THREAD

**Issue by thebutant** [KXStudio/Repository#168]
There's nothing new in this request, it was even suggested by falkTX.
But just to do it the proper way, I wish to suggest a package with plugins to VCVRack, preferably based on the GNU/Linux plugins found at VCVRack's own plugin site: https://vcvrack.com/plugins.html

A package like this would be great to have in the repos, as the VCVRack package provided by KXStudio does not allow users to install plugins on their own.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

VCVRack is one of those hard to build applications... perhaps the vst version is better, did not try yet
