### ISSUE TITLE
package-request: KXStudio-compatible Wine-rt 2 etc

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#169]
I see wine-rt 2.0 in Ubuntu repos, but installing it asks to remove wineasio andkxstudio-meta-wine etc

I'd like to update and see if I can run some things I've never gotten working before. I also seem to not have any wine-rt now, and I thought that was valuable for music but I may be mistaken.

**Comment by falkTX** [comment]
What distro is this?
In both Ubuntu 14.04 and 16.06 I can install wine-rt without issues.

Both wine-rt and wine-staging have the RT stuff inside.
But it's only usable if set from the command-line

**Comment by wolftune** [comment]
I'm on KDE Neon.

**Comment by wolftune** [comment]
I think I solved it. It was installing wine-rt-amd64 manually that had the problems. wine-rt package on its own got everything right and included wine-rt-amd64
