### ISSUE TITLE
package request: ctrlr

### ISSUE THREAD

**Issue by ewanuno** [KXStudio/Repository#17]
ctrlr is an editor for hardware midi synths. its the only decent one thats still being maintained.
its extensible, multiplatform, and it has a big user community.
unfortunatly its not very easy to compile, and only provides 64bit binaries so having it in kxstudio would be very useful for a lot of people.

http://ctrlr.org/

**Comment by ewanuno** [comment]
actually ctrlr snt hard to compile, it just needs a lot of memory to build. and my computers all have only 1gb ram.
nnother good thing in ctrlr is the vst plugin mode, which lets you use hardware synths in your daw just like softsynths.

**Comment by falkTX** [comment]
the project is cool, but not something I can assess if it works or not.
they have their own binaries, so I wont be packaging this
