### ISSUE TITLE
Ardour : forbidden midi notes

### ISSUE THREAD

**Issue by m4l3z** [KXStudio/Repository#171]
Hi @falkTX, thanks for the good work. 
I have found what I think is a bug in ardour. 
When using midi filters like your Midi Transpose or x42's midimap, the parameter related to notes/octaves doesn't correctly increment/decrement : some value are forbidden. 
![For Midi Transpose for example](https://user-images.githubusercontent.com/24318552/37353967-d298ce52-26e0-11e8-8bf2-b77b66b6872c.png) the values go from -8 to 8 but only those are allowed : -8,-7,-6,-4,-3,-1,1,2,4,5,7,8.
In the same fashion when trying to change parameters such as notes or CC the behavior is strange and some values are missing regularly.
If you need the whole list of values that disappear for those, tell me.
Finally, when using midimap, and loading my config file, ardour says it is unable to parse one line of the file, and this line precisely contains a value that ardour would "jump". 
Ardour 5.12.0 "Working Backwards" (rev 5.12)
libsuil-0-0 0.8.2~dfsg0-1
Linux Mint 18.1 with kxstudio repo

**Comment by falkTX** [comment]
Thanks for the report, but this needs to go upstream to ardour.

@x42 can perhaps comment here.

**Comment by x42** [comment]
This was fixed in https://github.com/Ardour/ardour/commit/a982a7cc6
Also there the click-box has meanwhile been replaced with a slider, but there has not been a release since.

**Comment by m4l3z** [comment]
Thanks for the heads up @x42, the workaround works ! 
Is it normal that the midimap config file is also affected by this behavior but not when writing my config directly in preset.ttl ?

**Comment by falkTX** [comment]
Closing this due to being external issue.
When ardour has a new official release, we can update to it.
