### ISSUE TITLE
Cadence - no auto-start and Force Restart

### ISSUE THREAD

**Issue by luciorgomes** [KXStudio/Repository#172]
The new version of Cadence does not auto-start Jack. And the "Force Restart" button crashes the app (error message: Unhandled Python exception / Abortado).
I need to start manually each item to run all Jack options ("Start", to start Jack; the same on Alsa Audio Bridge, and Export HW/ Start on Alsa Midi).
I'm on Linux Mint 18.3

**Comment by falkTX** [comment]
Thanks for the report.
I almost never use the force-restart option, so did not notice it was broken.

session-start was already fixed, but I forgot to push the fix to the repos.
in any case, these are all fixed now.
An update to the cadence repos will appear in the repos very soon.
