### ISSUE TITLE
Cannot launch Claudia (dbus error) on KDE neon

### ISSUE THREAD

**Issue by korakios** [KXStudio/Repository#173]
Hi,
I am on 
KDE neon 5.12
KDE plasma 5.44
QT version 5.10
4.13.0-37-lowlatency #42~16.04.1-Ubuntu SMP PREEMPT

When I try to launch Claudia from Cadence I get 
(DBus is not available, Claudia cannot start without it!)

Am I missing packages ? (KXStudio repos enabled)

**Comment by falkTX** [comment]
you're not missing packages. I added a fix (because neon broke pyqt5) to cadence main app, but forgot to add it to catia and claudia too.
commited now in latest git, updates to kx repo packages coming soon.
