### ISSUE TITLE
docs: please also add documentation of how to uninstall kxstudio

### ISSUE THREAD

**Issue by COLABORATI** [KXStudio/Repository#178]
Please add information on how to uninstall kxstudio after it leaves your system in an unusable state, thanks!

**Comment by jbmorgado** [comment]
Any news on this? I tried to remove kxstudio on Ubuntu 18.04 and now I can't install many packages 

For instance, `winehq-staging` gives the following error after trying to remove kxstudio:

```
sudo apt-get install --install-recommends winehq-staging
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 winehq-staging : Depends: wine-staging (= 3.20.0~bionic)
E: Unable to correct problems, you have held broken packages.
```

**Comment by mxa** [comment]
updating the distro (*ubuntu) always breaks kxstudio. It would be good to have this info somewhere how to properly remove it.

**Comment by mxa** [comment]
Also it's simply good practice to not only disclose how to install but also how to remove software. More people will be willing to try it when they know information is there how to properly remove it again.

**Comment by Lyberta** [comment]
First, you need to remove packages called "kxstudio-repos" and "kxstudio-repos-gcc5".

Then you need to revert all packages affected by kxstudio to default versions. In Synaptic go to "Installed (local or obsolete)" section, then for each package that you know from kxstudio, select it, click on "Package -> Force version...". There should be 2 versions: one marked (now) and one with the name of your distro. Choose the one with the name of your distro. Synaptic may offer you to change (usually install packages because kxstudio ones are outdated) some other packages, this is fine.

After that your rootfs should be more or less ok.

**Comment by ahellquist** [comment]
The procedure to remove kx-studio repos seems to be similar to changing from old repos to current new ones. I have looked for the information on the kxstudio site and elsewhere but I think that the only place this is documented is in IRC logs when the topic has been dsicussed.

It would be nice to have this information on https://kx.studio/Repositories for people not installing fresh. nothing fancy but just the basic procedure from author himself.

**Comment by falkTX** [comment]
It is a perfectly valid request.
I will add it to the FAQ, with a link on the main page linking to its html id tag.

**Comment by tvvoty** [comment]
Is this still an issue? Is disabling kxstudios repos from sources not enough? It seems to me like it just acts like another ppa now, am I wrong?

**Comment by mxa** [comment]
Related: https://www.reddit.com/r/linuxaudio/comments/ox6qm7/can_kxstudio_repositories_brake_my_system/

**Comment by falkTX** [comment]
uninstall and reinstall instructions have been added to https://kx.studio/Repositories:FAQ
