### ISSUE TITLE
Can't install kdenlive - unmet dependencies 

### ISSUE THREAD

**Issue by rghvdberg** [KXStudio/Repository#18]
sudo aptitude install kdenlive
The following NEW packages will be installed:
  dvdauthor{a} dvgrab{a} ffmpeg{a} katepart{a} kde-runtime{a} kde-runtime-data{a} kdelibs-bin{a} kdelibs5-plugins{a} kdenlive kdenlive-data{a} kdoctools{a} kubuntu-debug-installer{a} libkactivities-bin{a} libkactivities6{a} 
  libkatepartinterfaces4{a} libkcmutils4{a} libkde3support4{a} libkdeclarative5{a} libkdecore5{a} libkdesu5{a} libkdeui5{a} libkdewebkit5{a} libkdnssd4{a} libkemoticons4{a} libkfile4{a} libkhtml5{a} libkio5{a} libkjsapi4{a} 
  libkjsembed4{a} libkmediaplayer4{a} libknewstuff3-4{a} libknotifyconfig4{a} libkntlm4{a} libkparts4{a} libkpty4{a} libkrosscore4{a} libktexteditor4{a} libkubuntu0{a} libkxmlrpcclient4{a} libnepomuk4{ab} libplasma3{a} libqjson0{a} 
  libquicktime2{a} libsoprano4{a} plasma-scriptengine-javascript{a} qapt-batch{a} qt-faststart{a} recordmydesktop{a} soprano-daemon{a} 
0 packages upgraded, 49 newly installed, 0 to remove and 4 not upgraded.
Need to get 27.9 MB of archives. After unpacking 94.9 MB will be used.
The following packages have **unmet dependencies:**

 **libnepomuk4 : 
Depends: libkdecore5 (= 4:4.13.3-0ubuntu0.2) but 4:4.14.2-0ubuntu1~ubuntu14.04~ppa1 is to be installed.
Depends: libkdeui5 (= 4:4.13.3-0ubuntu0.2) but 4:4.14.2-0ubuntu1~ubuntu14.04~ppa1 is to be installed.**
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     kdenlive [Not Installed]                           
2)     libnepomuk4 [Not Installed]                        

     Leave the following dependencies unresolved:         
3)     kdenlive-data recommends kdenlive                  

Accept this solution? [Y/n/q/?]

**Comment by falkTX** [comment]
You're using the kubuntu backports ppa, right?
You'll have to ask them to include kdenlive in their repos.

**Comment by rghvdberg** [comment]
uhm .. not that I'm aware of
>deb http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu trusty main
deb http://dl.google.com/linux/chrome/deb/ stable main
deb http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/music/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu lucid main
deb http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/music/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu trusty main
deb http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu trusty main
deb-src http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu trusty main
deb http://kxstudio.linuxaudio.org/repo/ stable free
deb http://kxstudio.linuxaudio.org/repo/ gcc5 non-free
deb http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu trusty main
deb http://ftp.nluug.nl/os/Linux/distr/linuxmint/packages rosa main upstream import 
deb http://extra.linuxmint.com rosa main
deb http://ftp.nluug.nl/os/Linux/distr/ubuntu trusty main restricted universe multiverse
deb http://ftp.nluug.nl/os/Linux/distr/ubuntu trusty-updates main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse
deb http://archive.canonical.com/ubuntu/ trusty partner
deb http://deb.playonlinux.com/ trusty main
deb http://ppa.launchpad.net/recoll-backports/recoll-1.15-on/ubuntu trusty main
deb http://ppa.launchpad.net/rock-hopper/audiotools/ubuntu trusty main
deb http://repository.spotify.com stable non-free
deb http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu trusty main
deb http://download.virtualbox.org/virtualbox/debian trusty contrib

**Comment by rghvdberg** [comment]
figured out that Linux Mint has updated the kde packages.
I was able to install it with apitude (2nd solution it gives)
Closing this thread. It's not a KX Studio issue but a Mint issue.
