### ISSUE TITLE
[package request] mididings update

### ISSUE THREAD

**Issue by chaocrator** [KXStudio/Repository#180]
mididings in debian/ubuntu repos is outdated.
i experienced a lot of problems with it on ubuntu 16 and 18.
latest mididings version considered stable is from 2012-04-19. the project appears to be unmaintained for about 3 years, and the developer appears to be disappeared from the web.

there is a fork of mididings here:
https://github.com/ponderworthy/mididings

which has some issues fixed, and behaves MUCH better.
i myself use the latter, because the "original" mididings in it's current state can't even do many things according to its own manual.

my quick and dirty prototype build is available in my ppa:
https://launchpad.net/~chaocrator-ppa/+archive/ubuntu/audio/+packages

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
