### ISSUE TITLE
Many programs crashed in 18.04

### ISSUE THREAD

**Issue by MGdesigner** [KXStudio/Repository#181]
My distro is Ubuntu Mate 18.04. I installed KXstudio repos following [the Manual](http://kxstudio.linuxaudio.org/Repositories) as I installed on 16.04. 

After installing, Cadence, and Carla work all right, but many many audio applications  will crash with the same log:

 `free(): invalid pointer`

Hydrogen, Ardour,Audacity,rosegarden,LMMS, and etc .
It seems 18.04  repos lacks some dependency?  I have no idea what it is.

**Comment by falkTX** [comment]
Did you do a new install? or updated from 16.04?
One thing that could be happening here is a rogue ladspa plugin causing these crashes.
The often bad ones are `naspro-bridges` and `csladspa`. See if you have those installed, if yes, remove them.

**Comment by MGdesigner** [comment]
What I did  is a new installing .  I installed is Ubuntu Mate 18.04+ KXstudio repos.  After removing naspro-bridges and csladspa, it indeed helps! Amazing  !
