### ISSUE TITLE
feature request: add midi channel sensitivity to jack_mixer

### ISSUE THREAD

**Issue by tjingboem** [KXStudio/Repository#185]
We know Jack_mixer is dead, but we like its simplicity. Perhaps it is interesting to revive and improve it?
![jack_mixer](https://user-images.githubusercontent.com/6670911/41587733-2e54eb92-73b0-11e8-9596-147e6edb7bf7.png)

At the moment the mixer midi control inputs are sensitive to ALL midi channels. We would like to be able to set a certain midi channel to it so the we can use that midi track and midi channel for the Jack_mixer only.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
jack_mixer wont be in the new repos
