### ISSUE TITLE
Wine not working in Ubuntu 18.04 and Linux Mint 19

### ISSUE THREAD

**Issue by CG-3D** [KXStudio/Repository#186]
The wine, wine-rt and winecfg from the KXStudio-repository do not work in Ubuntu 18.04 (Desktop x64) and Linux Mint 19 Cinnamon (x64) due to a 'missing libpng12.so.0'.

For example, winecfg returns this error in the terminal:
err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0

I guess that Ubuntu 18.04 and Mint 19 use a newer version of libpng while wine(-rt) is still linked to the old version. Or maybe I am doing something wrong? I am not sure if the KXStudio repositories are supposed to work with these newer versions of Linux?

**Comment by CG-3D** [comment]
Wine seems to work fine now in both Ubuntu 18.04 and Mint 19 Cinnamon (both x64).
Thanks a million for the great work!

**Comment by stereoplegic** [comment]
I was under the impression that KXStudio 18.04 would be based on Neon, but my Neon 18.04 install still has dependencies with Wine. Installing it requires removal of not only KWin and several other critical KDE packages, but also several KXStudio packages. Using KXStudio repos based on both recommended debs (repos and repos-gcc5).

**Comment by CG-3D** [comment]
Actually, I have issues with KDE Neon (5.13.5, based on Ubuntu 18.04) as well. For example, if I try to install wine-rt-amd64 it complains about a missing libgif4:

The following packages have unmet dependencies:
 wine-rt-amd64 : Depends: wine-rt:any (= 2:3.0.2-1~kxstudio3v5)
                 Recommends: libgif4 but it is not installable

Is this version of Neon too 'bleeding-edge' to be used with KXStudio?

**Comment by falkTX** [comment]
neon does not have 32bit packages enabled by default, so you cannot install wine with it as-is.
this should get you wine-rt running:
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install wine-rt
```
let me know how that works.

**Comment by CG-3D** [comment]
After about 7 broken dependencies and their solutions it refuses to install wine-rt because:

    wine-rt : Depends: wine-rt-i386 (= 2:3.0.2-1~zz+bionic1)
               Recommends: ttf-droid but it is not installable or
                           fonts-droid but it is not installable

If I install wine-rt-i386 it fails as well:

     wine-rt-i386:i386 : Depends: libglib2.0-0:i386 (>= 2.12.0) but it is not going to be installed
                         Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not going to be installed
                         Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not going to be installed
                         Recommends: libgif4:i386 but it is not installable

And wine-rt-amd64:

    wine-rt-amd64 : Depends: wine-rt:any (= 2:3.0.2-1~zz+bionic1)
                     Recommends: libgif4 but it is not installable

As far as I can tell they link to / depend on an older font or libgif4?

**Comment by falkTX** [comment]
ah I remember this when I was preparing some base ISO things!

neon patches things and has custom versions of a few essential packages, but they only build for 64bit.
this means some essential packages that need to be installed as 32bit have no matching installable version.
libglib2 is one of such packages, which a lot of stuff depends on.

you can try the PPA I have for neon-stable: https://launchpad.net/~kxstudio-debian/+archive/ubuntu/kde5-neon/
if that also does not work, well, I am sad to say but it won't be possible to use almost anything 32bit together with official neon.

**Comment by falkTX** [comment]
oh, you might have some luck with wine-staging, as I believe they have some pure 64bit wine builds.
but yeah, getting 32bit stuff installed on neon is going to be a pain...

**Comment by CG-3D** [comment]
Actually, the PPA seems to work like a charm! Wine-rt installed fine and seems to work well. Will the PPA be available / grow with Neon in the foreseeable future?

I thank you very much once again!

**Comment by falkTX** [comment]
I plan to keep the PPA in sync with neon LTS.
The neon distro ISO images does not follow that. So I am not sure if at some point it will break or not...

**Comment by CG-3D** [comment]
I like KDE Neon enough to see how long it holds up. If it breaks, I'll adapt once again :).

**Comment by stereoplegic** [comment]
Works so far on latest Neon User Edition ISO with KXStudio Neon PPA, even without the recommended i386 enablement steps. 

My previous install was manually upgraded to 18.04 from 16.04-based Git-Stable, and any attempt to install wine-rt would have left me without KDE and several KXStudio packages.

Thanks for the tips, an amazing collection of software, and all your hard work!

**Comment by CG-3D** [comment]
Alas, ams-lv2 is not working either:

   ams-lv2 : Depends: libcairomm-1.0-1 (>= 1.6.4) but it is not installable
              Depends: libglibmm-2.4-1c2a (>= 2.24.0) but it is not installable
              Depends: libgtkmm-2.4-1c2a (>= 1:2.20.0) but it is not installable
              Depends: libpangomm-1.4-1 (>= 2.26.0) but it is not installable
              Depends: libsigc++-2.0-0c2a (>= 2.0.2) but it is not installable

I'll try if Neon LTS + PPA solves the issue in a VM...

**Comment by falkTX** [comment]
If you did an upgrade from an existing, older version of Neon or Ubuntu, you need to purge the repos and add them again.
@CG-3D that issue you list is exactly the one seen when you miss the gcc5 repos.

**Comment by CG-3D** [comment]
I reinstalled the gcc5 repo but the dependencies of ams-lv2 were still unmet. I also tried Neon LTS (in a VM) and it gave the same errors both with and without the PPA. Wine-rt installed fine though, even without the PPA.

**Comment by falkTX** [comment]
ok, thanks for checking.
Seems to be a problem specific to the ams-lv2 package, I will fix it and at the same time push an update to it.

**Comment by falkTX** [comment]
ok the ams-lv2 package is updated and fixed now.
I was able to install it on my 18.04 system.

**Comment by falkTX** [comment]
I am reworking the kx repos, wine and general applications are no longer supported 
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
