### ISSUE TITLE
Package request: QLC+

### ISSUE THREAD

**Issue by ciacnorris** [KXStudio/Repository#187]
http://www.qlcplus.org
It's not strictly ”audio”, but it can be great for managing audio and MIDI (and DMX of course) in live shows. Plus, KXStudio could be the ideal distro for using QLC+.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
