### ISSUE TITLE
Carla Bridge update error

### ISSUE THREAD

**Issue by luciorgomes** [KXStudio/Repository#192]
On today's update there is an error for the carla-bridge-wine64 package:

W: Não pôde encontrar https://github.com/KXStudio/Repository/releases/download/initial/carla-bridge-wine64_1.9.8.git20180819_amd64.deb
  404  Not Found [IP: 192.30.253.113 443]

**Comment by falkTX** [comment]
thanks for the heads up, I forgot something.
refresh software sources again, and it will be installable.
