### ISSUE TITLE
Carla issues on version 1.9.9+git20180903v5

### ISSUE THREAD

**Issue by luciorgomes** [KXStudio/Repository#193]
.In the first click on "+ Add plugin", after the startup of Carla, the "Add new" window takes 6 to 7 seconds to open. On the second time you click it loads normally.
.The "Show Custom UI" is disabled for 32 bits Windows Vsts. Only 64 bits ṕlugins are shown.

**Comment by falkTX** [comment]
Thanks for the interest.
Carla related things should go on https://github.com/falkTX/Carla/issues but anyway:
1- first open is expected to take longer, it scans internal, lv2 and sfz files.
if you added a big folder to the sfz paths with lots of nested folders inside, then I really expect this.
2- I noticed this too, this one is an actual bug, will fix it asap.

**Comment by falkTX** [comment]
Assume actual bug fixed, ticket should go to carla project anyway
