### ISSUE TITLE
I can't update the repository

### ISSUE THREAD

**Issue by lucmp** [KXStudio/Repository#194]
I just heard about konfyt. Its website says it's available from the KXStudio repository. But it isn't available to me.

So I went up to http://kxstudio.linuxaudio.org/Repositories
and followed all the instructions as if I hadn't done all that before (which I had, months ago).
The two .deb files installed normally on Debian Stretch.
I refreshed the package list.
But konfyt is still not there.
I refreshed the package list, but this time I took a screenshot and it seems there is something wrong with it. Please see for yourself.

![kx-error](https://user-images.githubusercontent.com/2882969/45531999-9a9b2080-b7c8-11e8-9ef8-23b14c82a4c4.png)

What should I do?

**Comment by falkTX** [comment]
konfyt is not on the kxstudio repos. I did not package it.
whoever told you it was there is lying.

**Comment by lucmp** [comment]
Well, maybe the application's page is outdated?
http://www.noedig.co.za/konfyt/

But what about those Failed status lines on Synaptic?

**Comment by falkTX** [comment]
The page is right. Carla is in the kxstudio repos, it does not refer to konfyt itself.

failed status is due to linuxaudio.org being down.
I dont know yet what is going on

**Comment by lucmp** [comment]
Shoot, you're right. I misread it. Sorry about that. Thank you.
