### ISSUE TITLE
Reaper not working after upgrade to ubuntu 18.04

### ISSUE THREAD

**Issue by xavs** [KXStudio/Repository#195]
Hi,
I'm experiencing problems after I upgraded ubuntu. when I start reaper now I get

`WINE realtime scheduling hack enabled, realtime base priority has been set to 55
wineserver running SCHED_FIFO at priority 70
fixme:heap:RtlSetHeapInformation 0x340000 0 0x22fc90 4 stub
fixme:heap:RtlSetHeapInformation 0x650000 0 0x2292c0 4 stub
fixme:heap:RtlSetHeapInformation 0x8a0000 0 0x2292c0 4 stub
fixme:heap:RtlSetHeapInformation 0x9f0000 0 0x229700 4 stub
fixme:heap:RtlSetHeapInformation 0xc20000 0 0x229700 4 stub
fixme:heap:RtlSetHeapInformation 0x9ea0000 0 0x229780 4 stub
wine: Unhandled page fault on read access to 0x00000008 at address 0x7fb55c6f1df9 (thread 0026), starting debugger...
winedbg: Internal crash at 0x7f536f846df9`

```
wine-rt --version
wine-2.0.1

```
Any ideas?

**Comment by pms967** [comment]
Try using the (newer) wine packages provided by Ubuntu instead of the ones provided by kxstudio. I'd also suggest to use a dedicated wine prefix, managed with "PlayOnLinux".

**Comment by ahellquist** [comment]
Why not using the linux version of Reaper ?

/Anders

Den ons 11 sep. 2019 kl 13:45 skrev pms967 <notifications@github.com>:

**Comment by pms967** [comment]
> Why not using the linux version of Reaper ?

Personally I do, most of the time... yet sometimes you need to use some windows VST plugins which are not available on Linux. Unfortunately to date running windows VSTs on the windows version of Reaper running under wine not only is more "comfortable" but (most importantly) works quite better than using Carla on the Linux version of Reaper.  Don't know why, but IME Carla creates a big performance penalty...

**Comment by falkTX** [comment]
I am reworking the kx repos, wine and general applications are no longer supported 
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
