### ISSUE TITLE
q_sort errors on SWH ladspa sifter plugin

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/Repository#20]
q_sort errors are reported both in console of freshly opened Ardour sessions and by Carla pertaining to the 'sifter' ladspa in the SWH collection. This doesn't seem to have noticeable detrimental performance effects but Ardour opening all sessions with a red error flagged in the console is kind of unsettling.

System reported from is Debian Stretch (AV Linux development) with KXStudio gcc5 repos enabled. This issue affects both 64 and 32bit systems.

*Ardour Console Error:
 [ERROR]: LADSPA: cannot load module "/usr/lib/ladspa/sifter_1210.so" (/usr/lib/ladspa/sifter_1210.so: undefined symbol: q_sort)

*Carla Console Error:
tester@avlinux64box:~$ carla-single ladspa /usr/lib/ladspa/sifter_1210.so sifter['/usr/lib/carla/carla-bridge-native', 'ladspa', '/usr/lib/ladspa/sifter_1210.so', 'sifter', '0']
libjack.so.0 loaded sucessfully!
Plugin failed to load, error was:
/usr/lib/ladspa/sifter_1210.so: undefined symbol: q_sort
tester@avlinux64box:~$

**Comment by AVLinux** [comment]
Just found this in case it helps:
 https://github.com/swh/ladspa/commit/93e8a911c95d43016754484d91eec78ef6a80a61

**Comment by falkTX** [comment]
swh-plugins package is now updated.
