### ISSUE TITLE
[package request] Orca

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#201]
Orca is an awesome "esoteric programming language", mainly used to make interesting little programs to control instruments via MIDI, OSC or UDP, and making it very useful for live-coded performances:

https://github.com/hundredrabbits/Orca

It would be wonderful to have that in the repos, as it is not yet a one-click install for Debian-based distros!

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
