### ISSUE TITLE
Package request: Strawberry instead of Clementine

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#202]
Fork seems more updated https://www.strawbs.org/

It already has deb for Ubuntu and such, just would be nice if the KXStudio repos included it, not super important thoough.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
