### ISSUE TITLE
dbgsym packages

### ISSUE THREAD

**Issue by mxa** [KXStudio/Repository#203]
I have an i[ssue with a crashing Pd](https://github.com/pure-data/pure-data/issues/591) which is pointing to jack2. To further investigate the root cause, I'm being asked to install the dbgsym packages, but they [don't seem to be published](https://nickhumphreyit.blogspot.com/2013/07/debugging-kxstudio-teams-musescore.html)?

**Comment by falkTX** [comment]
KXStudio packages are fully optimized, in order to make things work fast.
I have no interest on enabling debugging there.

**Comment by umlaeute** [comment]
debug packages are not about optimization settings, but about keeping the symbol information of binaries in a separate package.

whatever symbols get stripped away at the end of the packaging process (with something like `strip --strip-unneeded ...`) is collected in the ddeb packages.
the original package is as optimized as before, but if you install the ddeb package, you can run a proper backtrace in case of a crash.

**Comment by falkTX** [comment]
debug packages are not the same as debug symbols.

shipping with symbols is dangerous for audio plugins, as they can easily clash if exported functions have the same name (very hard to debug, specially on C++)

for performance-critical audio software, there is no other proper way but to disable debug and strip symbols.

**Comment by umlaeute** [comment]
i think there's some confusion of terms.

this is really about [ddeb](https://wiki.debian.org/DebugPackage)s - Debian Debug packages, which are *exactly* about debug symbols. these packages have nothing but debug symbols for a given binary package.

the binary packages are *identical* to the packages you already provide now. (they are optimized the same way; they have all symbols stripped).
if your package happen to [build reproducible](http://reproducible-builds.org/), you would notice that the resulting binary packages would be bit-for-bit identical, whether you enable debugging packages or not.

if they are identical, i expect them to have similar performance characteristics.

those package are not normally installed at all.
but if something goes wrong, they *can* be installed, and you can do meaningful debugging of your optimized packages, without modifying anything in your binary package.

**Comment by falkTX** [comment]
I will not be supporting this.
Due to heavy optimizations, even the symbols present they are often not very useful.
I am not even sure if these are possible to do in PPAs at this point, which kxstudio uses for its package build system.
