### ISSUE TITLE
package update request: lmms 1.2

### ISSUE THREAD

**Issue by chaocrator** [KXStudio/Repository#204]
the long-waited lmms 1.2 was at last released. 
please update.

**Comment by userabc123xyz** [comment]
I second this!

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For LMMS, I recommend to switch over to the new repos, remove the kxstudio packages of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
