### ISSUE TITLE
Package version problem w/ Helio Workstation

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#205]
You could package the update, but anyway I was able to simply test the .deb from https://helio.fm/

However, then the installed version is "2.0" and so apt tries to install the old KXStudio package "2:1.7+git20170831.2" over it, but that fails because it has outdated dependencies. Of course, it wouldn't make sense to go back to that 1.7 version actually.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For helio, I recommend to switch over to the new repos, remove the kxstudio package of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
