### ISSUE TITLE
Rosegarden and Muse are built against Qt4

### ISSUE THREAD

**Issue by Lyberta** [KXStudio/Repository#208]
As Debian is removing everything related to Qt4, they will not longer install soon. Debian provides newer versions of both apps in official repo. I think both Rosegarden and Muse can be just removed from KXStudio if you don't have time to maintain them.

**Comment by falkTX** [comment]
Yes, that will be the case soon. I have to put up an announcement

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For apps built with qt4, I recommend to switch over to the new repos, remove the kxstudio packages of these, and reinstall them again (which will be non-kxstudio versions now)
https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
