### ISSUE TITLE
No package named cadence

### ISSUE THREAD

**Issue by jbmorgado** [KXStudio/Repository#209]
After installing the `kxstudio-repos_10.0.2_all.deb` package on Ubuntu 18.04 and updating the repositories, no package named *cadence* shows up.

*carla* for instance does show up.

**Comment by falkTX** [comment]
Yes, I have not yet ported cadence into the new repos.
Will do soon, sorry for now you have to wait a bit

**Comment by falkTX** [comment]
Now fixed.
I am going to try to upload 2 packages per day from now on, but this is not a promise just a target, slowly we will get back on track again. Quite a few plugins are missing at the moment.

**Comment by jbmorgado** [comment]
Thank you.
