### ISSUE TITLE
Updating QTractor

### ISSUE THREAD

**Issue by manucontrovento** [KXStudio/Repository#210]
Hello everyone and thanks for the amazing and useful kxstudio tools!
My request is: would it be possible to keep up-to-date QTractor?
If I'm not wrong, at now QTractor on repos is at 9.6.0 version; since then many releases occurred and now it's at 9.10.0 release.
Thanks!
greetings from Italy
manu

**Comment by falkTX** [comment]
No, I stopped doing applications now.
While Qtractor is not the hardest thing to build, the author provides an AppImage, so there is not a super big need of kxstudio to have it in the repos.
See https://sourceforge.net/projects/qtractor/files/qtractor/0.9.10/
