### ISSUE TITLE
carla bridge packages, win vs wine?

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#211]
There's win and wine bridges, 32 and 64. The wine ones say "Dummy package". But the dependencies seem odd.

Any of removing win64 or wine32 *or* installing win32 will say it needs to remove carla-git etc and install regular carla. wine64 seems to have no connection (can be installed or removed, no issues).

Something is weird and confusing here.

**Comment by wolftune** [comment]
Still confused, but some interactions with dependencies seemed to relate to the outstanding wine install I had from old repos. I removed that and installed wine from outside repos.

Now, both "wine" bridges say "Dummy package" and both "win" ones look normal. And it appears that the one to install depends on how I've installed wine.

Anyway, I guess I'm clear enough now, it all seems working.

**Comment by falkTX** [comment]
I simplified the amount of packages needed for the bridges, but that also means dummy packages are needed for backwards compatibility (not to mention that carla is in ubuntu repos now too)

can you confirm again the issue regarding needing carla-git vs carla? ideally the bridges would work on both versions

**Comment by wolftune** [comment]
All I can say right now is that the old-repo legacy install of something was the issue. Once I cleared and reinstalled these bridges from the new repos, I couldn't reproduce the dependency issues.
