### ISSUE TITLE
Remove packages ll-scope and sineshaper as dependencies of kxstudio-recommended-audio-plugins-dssi

### ISSUE THREAD

**Issue by agusterol** [KXStudio/Repository#213]
I had a problem on Debian sid when installing package kxstudio-recommended-audio-plugins, because it tried to install kxstudio-recommended-audio-plugins-dssi, which depends on [ll-scope](https://packages.debian.org/search?keywords=ll-scope&searchon=names&suite=all&section=all) and [sineshaper](https://packages.debian.org/search?keywords=sineshaper&searchon=names&suite=all&section=all), which are not available for that version (they are for arm64 architecture, but not for amd64). Also they are neither available for stable version, nor for testing version.
In order to be able to install this meta package, I downloaded these packages from https://packages.ubuntu.com and it worked, but that's something I would like to avoid because it does not seem a good practice.

**Comment by falkTX** [comment]
Removed just now, next update of kxstudio-meta stuff will move those 2 to being a recommends instead of depends.
