### ISSUE TITLE
Where can I find the package for Ubuntu 16.04?

### ISSUE THREAD

**Issue by michaelsjackson** [KXStudio/Repository#214]
sudo dpkg -i kxstudio-repos_10.0.3_all.deb

requires Ubuntu 18.04.

**Comment by falkTX** [comment]
There is no such thing.
If you read https://kx.studio/Repositories, as you likely did, the repos now require 18.04

I encourage you to read https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back which explains the situation.

**Comment by michaelsjackson** [comment]
Thanks, usually for solving a minor problem (wineasio not working) one does not want to update to next ubuntu. Who knows which other problems this might bring for the thousands of programs on my harddisk.  Example: Updating emacs to 26.2 from 25.3 bringing lots of new troubles.  Never change a running system is a good key word.  Except wineasio not working here.  Thanks for the quick reply.

**Comment by falkTX** [comment]
wineasio or wine in general is not used in the new repos, so better to not update anyway
