### ISSUE TITLE
Can't  use kxstudio  repro on  debian buster

### ISSUE THREAD

**Issue by mitscherdinger** [KXStudio/Repository#216]
Hi!
I get an error message in aptitude if using the kxstudio repro, installed the usual way like it is described on the kxstudio-homepage - installing the kxstudio-repos.deb package:
"Failed to download some files
Failed to fetch http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu/dists/bionic/InRelease:        Failed to fetch http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/dists/bionic/InRelease:     Failed to fetch http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/dists/bionic/InRelease:        Failed to fetch http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu/dists/bionic/InRelease:"
The files are there. I can read them in my browser. And, of course,  I do have an internet connection. Somehow, the  repository can't seem to be discovered my Debian distribution. I'm  using Debian 10 (Buster) on a  64bit-intel-CPU. Strange. Don't know, how to resolve that.

**Comment by falkTX** [comment]
That is very odd... 

What is the error code written by apt? Please post here the entire output of `sudo apt-get update` thanks

**Comment by falkTX** [comment]
sorry, pressed wrong button by mistake

**Comment by mitscherdinger** [comment]
Get:8 http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu bionic InRelease [15.4 kB]
Get:9 http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu bionic InRelease [15.4 kB]
Get:10 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu bionic InRelease [15.4 kB]
Get:11 http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic InRelease [15.4 kB]
Reading package lists... Done       
E: Repository 'http://ppa.launchpad.net/kxstudio-debian/libs/ubuntu bionic InRelease' changed its 'Label' value from 'Libraries' to 'KXStudio Libraries'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu bionic InRelease' changed its 'Label' value from 'Plugins' to 'KXStudio Plugins'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu bionic InRelease' changed its 'Label' value from 'Applications' to 'KXStudio Applications'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic InRelease' changed its 'Label' value from 'KXStudio' to 'KXStudio Meta'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

Although I'm not quite sure how to fix that, yet, this seems to be the clue - haven't seen the apt-secure-hint in aptitude… So, not a bug in the kxstudio-package, at least.

**Comment by mitscherdinger** [comment]
Got it: I had to use "apt" instead of "apt-get" or "aptitude" to automatically get asked if apt should accept the new label  value.
