### ISSUE TITLE
Package request: TuxGuitar 1.3

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#22]
http://www.tuxguitar.com.ar/ yay, major release finally after many years. I tried their deb, and it runs, but the entire audio selection options seem missing. I can't tell what's going on with it. I think maybe it needs to be actually compiled with the right settings to work with JACK or something. I don't know.

**Comment by a13** [comment]
There was another issue with tuxguitar request :)

**Comment by wolftune** [comment]
okay oops
