### ISSUE TITLE
Surge Synth is a few revisions behind

### ISSUE THREAD

**Issue by tank-trax** [KXStudio/Repository#222]
Just a reminder that Surge Synth is now at version 1.6.5 and the KXStudio version is at 1.6.3

https://surge-synthesizer.github.io/

thanks

**Comment by falkTX** [comment]
Surge now at 1.6.5, added an extra patch to fix lv2 state. Though sadly it still does not work on carla, but it works on jalv according to a few users

**Comment by baconpaul** [comment]
Can you let me know where to find that patch so we pull into master? Or is it the one @jpcima put in a couple of days ago?
Thanks

**Comment by falkTX** [comment]
That is the one. I just grabbed that and manually apply it to the 1.6.5 tarball.

btw, this is quite off-topic, but I noticed the source tarball includes the .git directory, which increases the final tar by ~80Mb. Would be nice to remove that directory for the release source tarballs.

**Comment by baconpaul** [comment]
Oh thanks! The source tarball is a new feature and I just make it naively. I can definitely rm git before I pack it up.

**Comment by baconpaul** [comment]
OK modified our pipeline to remove the .git files. We are planning a 1.6.6 release this week (which includes that LV2 change). Either @tank-trax or I will open a new issue over here when it ships and the source tarball will be smaller by a bunch!
