### ISSUE TITLE
Add Muse3

### ISSUE THREAD

**Issue by grammoboy2** [KXStudio/Repository#223]
For some a good alternative to Ardour for midi. Matter of personal preferences

https://github.com/muse-sequencer/muse

**Comment by falkTX** [comment]
I am no longer packaging applications, see https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
> General applications and tools will not be supported anymore.

I do not use muse myself, and last time I checked there is quite a bunch of dependencies.
Better to ask them to provide binaries, like other projects like qtractor and lmms are doing now.
