### ISSUE TITLE
Repository certificate is expired

### ISSUE THREAD

**Issue by samoverton** [KXStudio/Repository#226]
After installing `kxstudio-repos_10.0.3_all.deb` and running `apt update` I get the following error.

    Get:14 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu bionic InRelease [15.4 kB]

    Err:15 https://kx.studio/repo stable Release                                                             
    Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 95.216.41.244 443]

    Get:16 http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic InRelease [15.4 kB]  

    Err:17 https://kx.studio/repo gcc5 Release                                                               
    Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 95.216.41.244 443]

**Comment by falkTX** [comment]
Fixed now.
I had a typo in one of the apache configs on the server, which prevented the certbot from auto-renewing https certificates.
