### ISSUE TITLE
Removing kxstudio-repos_10.0.3_all.deb does not remove repo from apt sources

### ISSUE THREAD

**Issue by samoverton** [KXStudio/Repository#227]
I installed `kxstudio-repos_10.0.3_all.deb` and then did

    apt remove kxstudio-repos

Then when running `apt update` I still see apt attempting to fetch from `https://kx.studio/repo`

    Hit:15 http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic InRelease
    Err:16 https://kx.studio/repo stable Release                         
    Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 95.216.41.244 443]
    Err:17 https://kx.studio/repo gcc5 Release                             
    Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 95.216.41.244 443]

The sources are still in `/etc/apt/sources.list.d/`

    $ ls -l /etc/apt/sources.list.d/kx*
    -rw-r--r-- 1 root root 735 Mar  8 07:49 /etc/apt/sources.list.d/kxstudio-debian-ppas.list
    -rw-r--r-- 1 root root 114 Sep  8 01:24 /etc/apt/sources.list.d/kxstudio-external.list

Expected behavior should be that removing the `kxstudio-repos` package should remove the repositories from the apt sources list.

**Comment by falkTX** [comment]
This is default behaviour of deb packages, they leave behind files in /etc as they are meant as configuration.
If you want to remove those files, you need to use the "purge" uninstall option

**Comment by falkTX** [comment]
This is now mentioned in https://kx.studio/Repositories:FAQ
