### ISSUE TITLE
Unable to install Carla on Kubuntu 20.04

### ISSUE THREAD

**Issue by esa1975** [KXStudio/Repository#229]
Kubuntu 20.04 has removed QT4 so Carla will no longer install.

```
The following packages have unmet dependencies:
 carla : Depends: libqtcore4 (>= 4:4.5.3) but it is not installable
         Depends: libqtgui4 (>= 4:4.6.1) but it is not installable
         Recommends: python3-rdflib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm not sure there's much you can do about it but I thought you should know. Thanks for the excellent work in KXStudio!

**Comment by rikmills** [comment]
To be clear, Qt4 has been removed completely from the Ubuntu archive for 20.04. While it is unlikely to get uninstalled for those upgrading to 20.04, it will not be available to new installations, and will not be re-installable if uninstalled. PPAs will no longer find Qt4 build dependencies in the Ubuntu archive when the build release is focal.

**Comment by a13** [comment]
there's `carla-git` package, which depends on qt5

**Comment by falkTX** [comment]
Both carla and carla-git do not depend on qt4 anymore
