### ISSUE TITLE
Package Request: OpenShot 2.0 beta

### ISSUE THREAD

**Issue by rghvdberg** [KXStudio/Repository#23]
I know it's beta but current version 1.4.3 is pretty useless :-)

https://launchpad.net/openshot/+download
http://www.openshotvideo.com/2016/01/openshot-20-beta-released.html

**Comment by falkTX** [comment]
I'm afraid I have to say no to this.
First for being a beta, but also because it uses MLT libs which I can't simply update without breaking other packages.

OpenShot should have some PPAs available, use that please.
Sorry.

**Comment by rghvdberg** [comment]
it's ok, discoverd the ppa's in the meantime
