### ISSUE TITLE
Cannot use the kxstudio version of ladish on Ubuntu 20.04

### ISSUE THREAD

**Issue by borgdylan** [KXStudio/Repository#231]
The python packages have been moved to use the python2 naming convention in 20.04. This seems to be the main blocker for using the ladish oackage shipped in kxstudio repositories.

**Comment by manhnt9** [comment]
I'd also like to know about KXStudio's plan for supporting Ubuntu 20.04.

**Comment by falkTX** [comment]
ladish author does not care about supporting python3, I am very tempted to just remove ladish altogether...
maybe it works with python3, I am not sure, but since it is not supported upstream, the burder of maintenance is on the distributions which is not very nice :(

**Comment by falkTX** [comment]
I just pushed an update, please try and let me know if ladish is installable now.
thanks.

**Comment by falkTX** [comment]
hello?

**Comment by lem11** [comment]
I just tried installing ladish (and gladish) from the KXStudio repo in a fresh install of Ubuntu 20.04 I had in a virtual machine.. both installed fine, and gladish launched fine too.. I don't use either so didn't do any testing, but seemed ok...

(thanks for all the work you do by the way falkTX, very much appreciated!)

**Comment by falkTX** [comment]
Thanks for confirming. I will close the issue then.
