### ISSUE TITLE
Linuxsampler-dssi (and zynaddsubfx-dssi): not a dssi or ladspa-plugin

### ISSUE THREAD

**Issue by mauritslamers** [KXStudio/Repository#233]
I am running Rosegarden, and I wanted to use LinuxSampler as instrument in Rosegarden. However, it doesn't show up after installing linuxsampler-dssi.

I checked using the `dssi_list_plugins` utility to check, and it reports:
```
-- warning: shared object '/usr/lib/dssi/linuxsampler.so' is neither a LADSPA nor DSSI plugin
```
it gives the same warning for zynaddsubfx-dssi btw. 

Running Ubuntu Linux 19.10, 64bit.

**Comment by falkTX** [comment]
linuxsampler has been fixed, will deal with zynaddsubfx later

**Comment by falkTX** [comment]
zynaddsubfx-dssi now fixed too. thanks for the report, good catch!

**Comment by mauritslamers** [comment]
Thanks for fixing!
