### ISSUE TITLE
E: Package 'cadence' has no installation candidate

### ISSUE THREAD

**Issue by clendee** [KXStudio/Repository#234]
I recently update to 'Mate 20.04', perhaps somewhat prematurely.  I cannot currently install any software from the kxstudio repos.  I'd love to see a fix to this as Im rather reliant on these repos.

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package cadence is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cadence' has no installation candidate`

**Comment by clendee** [comment]
Thank you, this has been fixed now.

**Comment by trebmuh** [comment]
@clendee : mind writing "how" for people reading?

**Comment by falkTX** [comment]
I guess I replied to this via email somehow..

You just need to purge the kxstudio-repos package and install it again
