### ISSUE TITLE
Repositories not added in Ubuntu 20.04

### ISSUE THREAD

**Issue by hellocatfood** [KXStudio/Repository#235]
I'm trying to install the repositories on Ubuntu 20.04. Double-clicking on the .deb just opens the archive manager (for unzipping). Running ` sudo dpkg -i kxstudio-repos_10.0.3_all.deb` appears to install it but the repositories aren't actually added. I've checked /etc and don't see the repositories when I run `apt update`

**Comment by falkTX** [comment]
Did you do an OS update from older versions of ubuntu?
Because in that case you need to purge and reinstall the repo package.

**Comment by hellocatfood** [comment]
Thanks for the quick response. Yes, that appeared to be the problem.

**Comment by mikeperalta1** [comment]
+1 purging fixed it for me. Too bad there isn't an easily apparent way to know this.

**Comment by hellocatfood** [comment]
Could these instructions be added to the website?

**Comment by Moth-Tolias** [comment]
how do you purge?

**Comment by falkTX** [comment]
`sudo apt-get purge kxstudio-repos`

**Comment by Moth-Tolias** [comment]
thank you, that worked wonderfully.

**Comment by falkTX** [comment]
A note about reinstall/upgrade was added in https://kx.studio/Repositories:FAQ
