### ISSUE TITLE
Install Problem in Ubuntu 

### ISSUE THREAD

**Issue by Ehsan-Ebrahimi** [KXStudio/Repository#237]
Hallo everyone,

i have this Problem with Install in Ubuntu

ehsan@ehsan:~$ sudo dpkg --purge kxstudio-repos-gcc5
dpkg: warning: ignoring request to remove kxstudio-repos-gcc5 which isn't installed

thanks
Ehsan

**Comment by falkTX** [comment]
that is not an error, it is quite. so you do not have the package already.
move on to the next step

**Comment by Ehsan-Ebrahimi** [comment]
Thanks Filipe
