### ISSUE TITLE
Helm LV2 missing presets

### ISSUE THREAD

**Issue by jhammen** [KXStudio/Repository#24]
package _helm_ 2:0.6.1+git20160105-1kxstudio1 (trusty)

Helm works as installed from ppa, presets are available via the browse button in the GUI but there are no  LV2 presets available - installing Helm from source shows all presets available via LV2 as well

behavior confirmed in Ardour + lv2info

Thank you for packaging Helm!

**Comment by falkTX** [comment]
I think helm is looking for /usr/share files during build, which don't exist while building on the ppa.
I'll try something, when you see the helm update try it out and let me know if it works.

**Comment by falkTX** [comment]
fixed now

**Comment by jhammen** [comment]
confirmed. thanks!
