### ISSUE TITLE
Missing libjack-jackd2-dev in ARMHF repo (Raspberry Pi)

### ISSUE THREAD

**Issue by mark-orion** [KXStudio/Repository#240]
The KXStudio repo updates libjack-jackd2-0 to version 1.9.14 but not libjack-jackd2-dev that is stuck at 1.9.12. Please provide a matching libjack-jackd2-dev so that jackd programs can be compiled from source.

**Comment by falkTX** [comment]
the package is there though.
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/ubuntus/+sourcepub/10806628/+listing-archive-extra

**Comment by kwalker99** [comment]
This is also missing for amd64, apt wants to use the distro dev lib...

**Comment by falkTX** [comment]
The "extras" repo that had jackd2 package is no longer supported, see https://kx.studio/News/?action=view&url=changes-in-kxstudio-repositories-2
It is no longer possible to build these packages properly.
