### ISSUE TITLE
FFADO packages are missing epoch value

### ISSUE THREAD

**Issue by unDocUMeantIt** [KXStudio/Repository#241]
KXStudio currently offers FFADO 2.4.2 packages, but at least in ubuntu 18.04 there are also 2.3.0 packages (e.g., i see both `2.4.2-1` and `2:2.3.0+svn2652-1~kxstudio1v5` for `libffado2`). the older package is configured to epoch 2 (mind the `2:` prefix), so you cannot simply upgrade to the newer package because apt considers it to be the older one.

i suggest to add an epoch value of 2 to the newer package as well, so it will be installed during updates.

**Comment by falkTX** [comment]
I think you have an old package from where I used to package those.
I do not want to have bumped epoch versions for packages outside the apps/plugins stuff.

You can just manually install the proper ffado package and all should be fine.
```
sudo apt-get install libffado2=2.4.2-1 ffado-dbus-server=2.4.2-1 ffado-tools=2.4.2-1
```

**Comment by unDocUMeantIt** [comment]
seems to have worked, thanks. i also had to purge the legacy repos to not have the old package reappear.
