### ISSUE TITLE
Sequencer64 segfault on Kubuntu 20.04

### ISSUE THREAD

**Issue by markussundstrom** [KXStudio/Repository#244]
sequencer64_0.96.7+git20200229_amd64
Kubuntu 20.04 with Ubuntu studio and KXStudio added.
Segmentation fault, steps to reproduce:
Start Sequencer64
Doubleclick pattern slot in main window to open a new pattern in pattern editor.
Close pattern editor window - Segmentation fault.

**Comment by falkTX** [comment]
I just updated seq64 to latest version, please give it a try.
I am not able to reproduce this specific issue in here, so I guess it is fixed now.

**Comment by markussundstrom** [comment]
Updated and did a quick test, seems to work just fine now. Thank you!
