### ISSUE TITLE
jalv dependencies

### ISSUE THREAD

**Issue by daveriedstra** [KXStudio/Repository#246]
Installing `jalv` with apt doesn't seem to bring in the right dependencies (or at least, it didn't on my system, Pop!_OS 20.04). I'm not sure if this is a packaging thing or an issue with the software itself; let me know if I should be reporting this on the jalv repo.

running right after install shows
```
suil error: Failed to open module /opt/kxstudio/lib/suil-0/libsuil_x11.so (/opt/kxstudio/lib/suil-0/libsuil_x11.so: cannot open shared object file: No such file or directory)
error: failed to open file /home/dried/.lv2/AuburnSoundsPanagement2.so/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///home/dried/.lv2/AuburnSoundsPanagement2.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/dried/.lv2/AuburnSoundsPanagement2.so/manifest.ttl
Missing plugin URI, try lv2ls to list plugins
```

installing `libsuil-x11-in-gtk3` and `liblilv-0-0` doesn't help

**Comment by falkTX** [comment]
this has been fixed in the updated repos, a `libsuil-kxstudio` is available and set as jalv dependency
