### ISSUE TITLE
Surge 1.7.1

### ISSUE THREAD

**Issue by baconpaul** [KXStudio/Repository#247]
Hi @falkTX 

Just FYI: we released Surge 1.7.1 this morning!

tag release_1.7.1
branch release/1.7.1

Releases should get a bit more regular now that we did the big push from 166->170

Thanks!

**Comment by baconpaul** [comment]
Just bumping this issue since we went to 1.7.1 this morning

**Comment by falkTX** [comment]
Now in the kxstudio repos! :)

Some tiny bits needed fixing, but all good now.
Still need a way to clearly set version in the plugin, but will leave that for later.

**Comment by baconpaul** [comment]
Great! 

I'm thinking what I'll do is eject a version file into the tarball from the pipeline and read that in cmake. Will add an issue and do it for 1.7.2.
