### ISSUE TITLE
Latest Cadence update broke JACK audio - Ubuntu 18.04

### ISSUE THREAD

**Issue by casper** [KXStudio/Repository#248]
After using Cadence and Jack without problems for many months, today I updated Cadence from the KXStudio repos and it blew my Ubuntu 18.04 audio setup to smithereens.

I am on Cadence 2:0.9.0+git20180427v5 and jackd2 2:1.9.14+git20191216.2.

Now whenever I log in, it seems DBus runs `jackdbus auto`, and there is no way to stop it. As a result Cadence cannot start JACK, with message "Failed to start JACK, please check logs for more information.".  

In syslog I see only:
`org.jackaudio.service[1774]: ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
`
My `ps` output shows:

 ```
 1423 ?        Ss     0:00 /lib/systemd/systemd --user
 1428 ?        S      0:00  \_ (sd-pam)
 1774 ?        Ss     0:00  \_ /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
 1783 ?        Ss     0:01  \_ /usr/bin/jackdbus auto
 1785 ?        S      0:01  \_ /usr/bin/a2jmidid dbus
```

There is no way to kill this jackdbus process. kill -9 and it just comes back from the dead. There is no systemctl service that I can figure out which runs it either. Where did it come from?

In any case to me it looks like systemd took control of jackdbus, when previously it was Cadence that did this task. Nothing works now...nothing is visible in Catia either. No inputs or outputs. Rebooting does not help either, and Cadence shows no JACK process running at all. 

How do I fix this? 
Any way to debug this further to try and figure out why systemd wants to control jack? 
I'm assuming systemd is not supposed to be running jackd, but Cadence should be doing it instead?

**Comment by falkTX** [comment]
the jackdbus process is normal and expected. as long as cadence is running, it will make it auto-spawn again.

you can try the following:

for fully restarting audio:
```
cadence-session-start -s
```


to clear all audio configs:
```
cadence-session-start --reset
```

I have not pushed an update to cadence in quite some time, so that is likely not the source of the issue.

**Comment by casper** [comment]
Thanks. Output was as follows:

```
$ cadence-session-start -s

Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence_session_start.py", line 239, in <module>
    sys.exit(startSession(False, False))
  File "/usr/share/cadence/src/cadence_session_start.py", line 119, in startSession
    startJack()
  File "/usr/share/cadence/src/cadence_session_start.py", line 150, in startJack
    DBus.jack.StartServer()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.jackaudio.Error.Generic: Failed to open server

$ cadence-session-start --reset
```

Even though the first command gave an error, it seems to work now!
So perhaps it was just a corrupted config? 

Anyway, both Cadence and Catia seems to be back online now.
Great :) I will run some tests and make sure everything works. But looks good.
