### ISSUE TITLE
Package request: DIN update

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#25]
Currently, I only have Din 5, and major tons of releases have been done so it's now on version 25!!! Source: http://dinisnoise.org/download/

Would be great to package the update in KXStudio, thanks!

**Comment by wolftune** [comment]
Oh wow wow wow wow!!!!!!!!!!!!!!!!  DIN 25 is available for compilation on GNU/Linux! Same link as above, updated the request. I'm so excited to try this. I could figure it out on my own although I've never even used svn. This would be so great to have in KXStudio!

**Comment by wolftune** [comment]
I would so love to get this in KXStudio for myself and others. It doesn't seem too hard to do, but the dependencies aren't clearly listed for Ubuntu based systems. Plus, it's inefficient for me to do all the figuring out locally just for myself. I'd really love to see this in the repos for everyone. What can I do to help get this?

Side-note: the newer versions have a MUCH easier to use interface where it's way easier to learn how to use it. Getting to that is what matters. Even though it would be nice to keep updating later, I'd be pretty fine with getting the current version now even if that stayed stagnant for a while afterward…

**Comment by wolftune** [comment]
update: 26 is out now, heard reports that packaging works smoothly, still a bit beyond me though and would like to see it for all KXStudio users.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

even though DIN is quite nice, I will not use it myself
