### ISSUE TITLE
LADSPA cmt seems to miss some stuff when loading in AMS

### ISSUE THREAD

**Issue by grammoboy2** [KXStudio/Repository#254]
I get these messages when opening "example_ams_demo.ams"  in ams in Debian testing. When I downgrade the package from kxstudio to plain Debian, it seems to be fixed.

Could not find LADSPA plugin "Canyon Delay" from library "cmt".

Could not find LADSPA plugin "Freeverb (Version 3)" from library "cmt"

**Comment by falkTX** [comment]
Same issue as #258, fixed in 1.17-1kxstudio2 package update
