### ISSUE TITLE
Hydrogen-drumkits XML needs update

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#26]
the hydrogen-drumkits package does work, but there's some minor glitches.

terminal output has errors for each entry that are like this:

```
Error XSDError in file:///usr/share/hydrogen/data/drumkits/ErnysPercussion/drumkit.xml, at line 1, column 14: No definition for element drumkit_info available.
```

and

```
(E) XMLDoc::read XML document /usr/share/hydrogen/data/drumkits/ErnysPercussion/drumkit.xml is not valid (/usr/share/hydrogen/data/xsd/drumkit.xsd), loading may fail
```

And I think this may be related to the fact that Hydrogen doesn't recognize some of these as being the same as some items from the source lists to download.

I suspect just an info bit is expected or some other format is supposed to be altered to make the same kits have XML forms that matches newer Hydrogen expectations.

A few other errors arise with:

```
(E) Filesystem::check_permissions /usr/share/hydrogen/data/drumkits/Millo-Drums_v.1/emptySample.wav is not a file
(E) Sample::load Unable to read /usr/share/hydrogen/data/drumkits/Millo-Drums_v.1/emptySample.wav
```

The whole issue there is that the files are all now .flac instead of .wav, so the info just needs to be updated accordingly.

**Comment by wolftune** [comment]
Oh, someone did other important updates that could be included in an update here
https://musical-artifacts.com/artifacts/133

They don't seem to have fixed any of the issues above, and they seem to omit some of the kits for reasons I don't understand. Would be nice to consolidate this work.

**Comment by lfzawacki** [comment]
These were created by the user asbak in the linuxmusicians forum https://linuxmusicians.com/viewtopic.php?f=50&t=14587

He'd probably be willing to get these changes upstream to hydrogen

**Comment by falkTX** [comment]
I've updated the hydrogen-drumkits package to the latest debian version, and added the asbak's stuff.
There are some warnings when running hydrogen due to some kits being in old format, but they still work.

Please test and let me know if anything's missing.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

hydrogen wont be in the new repos, sorry
