### ISSUE TITLE
Python 2 end-of-life consequences

### ISSUE THREAD

**Issue by Ghostbird** [KXStudio/Repository#261]
Is there any plan to support python 3 based distributions soon? 
I understand depending on how the code base is structured, a move to Python 3 is either a quick fix, or an utter dependency hell.

#### My reason for asking is:

I did an update to Debian 11 (in the last phases of testing before being released), and now my apt-get cannot do a dist-upgrade because:
```
The following packages will be REMOVED:
  android-tools-fsutils cadence claudia cython gladish ladish libpython-all-dev …
```
The `python` package is no longer in the Debian 11 repositories, as the OS has (finally) moved to Python 3. There's a lot more python2 tools that will be removed, because they have been replaced with python3 based tools. However specifically the set `cadence claudia gladish ladish` is what keeps my system in a weird state with packages being kept back.

If there's no plan to move to python3 in place. Would your recommend removing the Debian repository KXStudio repository and installing the loose binaries from the website? Or are those still dependent on a system installed Python2?

**Comment by falkTX** [comment]
python2 should not be needed for anything in the kxstudio repositories.
I simply do not have a system where I am able to uninstall python2 to test this.

if you are able to make a list of such packages, I can take a look.
or perhaps there is already a docker image for debian 11, I could use that for testing...

ladish dependencies in the kxstudio repos have'
```
Version: 5:2~git20140911-1kxstudio3
Depends: libc6 (>= 2.14), libdbus-1-3 (>= 1.9.14), libexpat1 (>= 2.0.1), libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125, libuuid1 (>= 2.16), jackd, python3-dbus
Recommends: a2jmidid
```
so it is not clear to me where the python2 dependency comes from...

**Comment by Ghostbird** [comment]
Thanks for your speedy reply. I may have been mistaken, and I will look into this further. Probably next week.

**Comment by Ghostbird** [comment]
I looked further into this, and realised that due to an error in my set-up, the KXStudio packages were stuck at older versions that were in some way still dependent on python2. I fixed my set-up and have updated my system successfully. Thanks for quickly pointing out that the error was clearly on my side.
