### ISSUE TITLE
Can not install kdenlive because libnepomuk

### ISSUE THREAD

**Issue by COLABORATI** [KXStudio/Repository#27]
When trying to install kdenlive I get this error:
```
kdenlive : Depends: libnepomuk4 (>= 4:4.5.85) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

But there are no held packages on that system. Whats going on here?

Thanks!

**Comment by falkTX** [comment]
See #18 it might be the same issue.

**Comment by COLABORATI** [comment]
I removed kubuntu backport repos and after that it seems to work ok. 
Are you planning to support new kdenlive releases (now versioned like '15.12.1') ?

**Comment by falkTX** [comment]
glad to know it's working now. (I'll close the bug now)

regarding updated kdenlive packages, I'm afraid it's not possible.
new kdenlive requires KDE5..
