### ISSUE TITLE
package request: pipewire 

### ISSUE THREAD

**Issue by Supermagnum** [KXStudio/Repository#276]
PipeWire is a project that aims to greatly improve handling of audio and video under Linux. It provides a low-latency, graph based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both pulseaudio and JACK. PipeWire was designed with a powerful security model that makes interacting with audio and video devices from containerized applications easy, with supporting Flatpak applications being the primary goal. 

It can be built from source, link below:
https://pipewire.org/

It is also available in a PPA:
https://pipewire-debian.github.io/pipewire-debian/

**Comment by falkTX** [comment]
sorry, that is a no.
pipewire is a system library that integrates deeply with other systems.
arbitrarily updating pipewire without the rest of the system (desktop environment, system libs etc) is not a good idea.
