### ISSUE TITLE
package request: harmonySEQ

### ISSUE THREAD

**Issue by chaocrator** [KXStudio/Repository#28]
https://harmonyseq.wordpress.com/
harmonySEQ is a live loop-based MIDI software sequencer with significant amount of uniquie features unavailable elsewhere.
in particular:
«harmonySEQ can easily cope with very complex polyrhythms, which is an original feature. You can achieve that by selecting different time signatures for each sequencer. However, most sequencer get easily confused, if simultaneously played melodies are – for example – in 3/4 and 4/5. harmonySEQ easily deals with this problem, and will automatically synchronize these melodies for you!»

**Comment by chaocrator** [comment]
well… managed to package it myself.
currently for xenial only. trusty & bionic builds will appear soon.
https://launchpad.net/~chaocrator-ppa/+archive/ubuntu/audio

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
