### ISSUE TITLE
Unable to install jackd2 - Dependencies conflict with wineHQ.

### ISSUE THREAD

**Issue by moonshaadow** [KXStudio/Repository#280]
Hi there.
I cannot install jackd2 when wine is installed from winehq ppa.

Dependencies errors brings me here, trying to install `libjack-jackd2-0` which is a dependency for `jackd2` : 
```
sudo apt install libjack-jackd2-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gstreamer1.0-plugins-base:i386 libapparmor1:i386 libasn1-8-heimdal:i386
  libasound2:i386 libasyncns0:i386 libatomic1:i386 libavahi-client3:i386
  libavahi-common-data:i386 libavahi-common3:i386 libbrotli1:i386 libbsd0:i386
  libcairo2:i386 libcap2:i386 libcdparanoia0:i386 libcups2:i386
  libcurl3-gnutls:i386 libdbus-1-3:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386
  libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386
  libelf1:i386 libexif12:i386 libexpat1:i386 libffi7:i386 libflac8:i386
  libfontconfig1:i386 libfreetype6:i386 libgd3:i386 libgdbm-compat4:i386
  libgdbm6:i386 libgl1:i386 libgl1-mesa-dri:i386 libglapi-mesa:i386
  libglib2.0-0:i386 libglu1-mesa:i386 libglvnd0:i386 libglx-mesa0:i386
  libglx0:i386 libgmp10:i386 libgnutls30:i386 libgphoto2-6:i386
  libgphoto2-port12:i386 libgssapi-krb5-2:i386 libgssapi3-heimdal:i386
  libgstreamer-plugins-base1.0-0:i386 libgstreamer1.0-0:i386
  libhcrypto4-heimdal:i386 libheimbase1-heimdal:i386 libheimntlm0-heimdal:i386
  libhogweed5:i386 libhx509-5-heimdal:i386 libicu66:i386 libieee1284-3:i386
  libjbig0:i386 libjpeg-turbo8:i386 libjpeg8:i386 libk5crypto3:i386
  libkeyutils1:i386 libkrb5-26-heimdal:i386 libkrb5-3:i386
  libkrb5support0:i386 libldap-2.4-2:i386 libllvm12:i386 libltdl7:i386
  libmysqlclient21:i386 libnettle7:i386 libnghttp2-14:i386 libodbc1:i386
  libogg0:i386 libopenal1:i386 libopus0:i386 liborc-0.4-0:i386 libosmesa6:i386
  libp11-kit0:i386 libpcap0.8:i386 libpci3:i386 libpciaccess0:i386
  libperl5.30:i386 libpixman-1-0:i386 libpng16-16:i386 libpsl5:i386
  libpulse0:i386 libroken18-heimdal:i386 librtmp1:i386 libsamplerate0:i386
  libsane:i386 libsasl2-2:i386 libsasl2-modules:i386 libsasl2-modules-db:i386
  libsdl2-2.0-0:i386 libsensors5:i386 libsndfile1:i386 libsndio7.0:i386
  libsnmp35:i386 libsqlite3-0:i386 libssh-4:i386 libssl1.1:i386
  libstdc++6:i386 libtasn1-6:i386 libtheora0:i386 libtiff5:i386
  libusb-1.0-0:i386 libv4l-0:i386 libv4lconvert0:i386 libvisual-0.4-0:i386
  libvkd3d-shader1:i386 libvkd3d1:i386 libvorbis0a:i386 libvorbisenc2:i386
  libvulkan1:i386 libwayland-client0:i386 libwayland-cursor0:i386
  libwayland-egl1:i386 libwebp6:i386 libwind0-heimdal:i386 libwrap0:i386
  libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386
  libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-randr0:i386
  libxcb-render0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386
  libxcb1:i386 libxcomposite1:i386 libxcursor1:i386 libxdmcp6:i386
  libxext6:i386 libxfixes3:i386 libxi6:i386 libxinerama1:i386
  libxkbcommon0:i386 libxml2:i386 libxpm4:i386 libxrandr2:i386
  libxrender1:i386 libxshmfence1:i386 libxss1:i386 libxxf86vm1:i386
  mesa-vulkan-drivers:i386 ocl-icd-libopencl1:i386
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  jackd2
The following packages will be REMOVED
  libasound2-plugins:i386 libjack-jackd2-0:i386 wine-stable:i386
  wine-stable-i386:i386 winehq-stable
The following NEW packages will be installed
  libjack-jackd2-0
0 to upgrade, 1 to newly install, 5 to remove and 0 not to upgrade.
Need to get 242 kB of archives.
After this operation, 619 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.

```

The opposite issue occurs when jackd2 is first installed : then I'm unable to install wine from winehq ppa.

_Linux Mint   20.03, based on Ubuntu focal_

**Comment by moonshaadow** [comment]
This seems strange : please look at version of `libjack-jackd2-0:i386`, which seems to be a dependency of wine :
![Screenshot_2022-02-03_17-18-16](https://user-images.githubusercontent.com/29754932/152384176-dbe51d63-091b-431f-a3d8-4f5158d7be2b.png)

**Comment by falkTX** [comment]
yeah, the builder fails on i386. no idea why since it works for everything else, and was working just fine before.
I have triggered a rebuild just in case https://launchpad.net/~kxstudio-debian/+archive/ubuntu/ubuntus/+build/23061562

**Comment by moonshaadow** [comment]
Hi.
Are there any ideas about that ?
I would like to find a work-around to have a clean install with jack + recent wine, but I'm still unable to have both side to side.

**Comment by falkTX** [comment]
well I am trying a few things, but the i386 build always fails before it even starts.
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/ubuntus/+sourcepub/13261847/+listing-archive-extra

as I said, everything else works, and this same exact build was working some weeks ago.
so dont really know how to fix, sorry

**Comment by moonshaadow** [comment]
Just FYI, 
Debian package seems to be [successful](https://buildd.debian.org/status/fetch.php?pkg=jackd2&arch=i386&ver=1.9.20%7edfsg-1%2bb1&stamp=1643225373&raw=0).

**Comment by Yo-L-B** [comment]
Hi!
With the release of jackd2 1.9.21, could you please have a try at fixing this issue?
I'm sorry for not being able to help that much as I'm not proficient enough in CI/CD. All I could see in those logs was
```
The following packages have unmet dependencies:
 sbuild-build-depends-jackd2-dummy : Depends: cdbs but it is not going to be installed
                                     Depends: debhelper (>= 9) but it is not going to be installed
```
If you give me a path to where I could have a look, I'm more than willing to get a foot in launchpad and have a try at fixing this, no guarantees on the result though as I will have to learn at the same time.

Background:
I'm using [yabridge](https://github.com/robbert-vdh/yabridge) (which is really great by the way) that depends on WineHQ, which itself needs the i386 architecture and as explained by moonshadow, right now we can't have both jackd2 and winehq :(

**Comment by falkTX** [comment]
Just spent some time looking into this, I think I understand the situation now.
A few months ago Ubuntu has disabled i386 PPA builds (on 20.04 onwards) for all packages except those that are part of 20.04 release.

This is more or less explained in this forum thread, that with 20.04 the i386 part of the repos is quite limited
https://discourse.ubuntu.com/t/community-process-for-32-bit-compatibility/12598

You can see this for yourself on https://launchpad.net/~kxstudio-debian/+archive/ubuntu/libs/+packages?field.series_filter=focal
The [libopus-custom-static - 2:1.3.1-1kxstudio1](https://launchpad.net/~kxstudio-debian/+archive/ubuntu/libs/+sourcepub/11647556/+listing-archive-extra) package that was built in late 2020 has i386 builds published, but the new [opus-static - 3:1.3.1-1kxstudio5](https://launchpad.net/~kxstudio-debian/+archive/ubuntu/libs/+sourcepub/13431669/+listing-archive-extra) does not have i386.

I tried a couple of things but I see nothing that special that differs between the 2, so my conclusion is that i386 builds on 20.04 PPAs are just not possible anymore.

After some online searches, I found these related discussions and tickets:
https://discourse.ubuntu.com/t/i386-packages-in-launchpad-ppas/15367
https://answers.launchpad.net/launchpad/+question/701011
https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1965800

There doesn't seem to be any interest from Canonical/Ubuntu's side to fix this, as the removal of i386 stuff is quite intentional.

So I don't see a way to get this to work again either.
The i386 packages are still quite relevant to me and many users, but we cannot build them anymore.
A way to go would be to just leave launchpad, but there really isn't anything like it out there that I know. And doing all the builds myself is not something I have time and capability for at the moment.

**Comment by moonshaadow** [comment]
A (not very acceptable) work around is to temporarily deactivate kx repos and remove all related jack and cadence stuff, then install jack from Ubuntu, and then reactivate kx repos and reinstall cadence and others things needed. It ends with an old jack and libjack:i386 version (1.9.12), but we could install wine-staging after that.
Another non-acceptable work-around is to change your distro... Debian and manjaro are working, I suppose mx-linux and AVlinux too...

**Comment by falkTX** [comment]
The last build I did on the kxstudio PPAs was exactly an attempt at building their package. And that fails too.
i386 PPA builds are simply broken right now, as described in https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1965800

Even if this is fixed, it is likely going to break again. No one is really caring for such builds to be broken it seems.

**Comment by falkTX** [comment]
btw, you can see that build status here https://launchpad.net/~kxstudio-debian/+archive/ubuntu/ubuntus/+build/23557669

**Comment by falkTX** [comment]
oh, also note we cant use the ubuntustudio backports packages directly (that is, copy from one PPA to the next), because they do not have ARM builds enabled.

**Comment by falkTX** [comment]
The extras repo is now deprecated and should not be used anymore.
See https://kx.studio/News/?action=view&url=changes-in-kxstudio-repositories-2 for details, including how to get back a working system (just with outdated jack)
