### ISSUE TITLE
mod-cv-plugins are missing mod overlays from lv2-data-creative-commons

### ISSUE THREAD

**Issue by steveb** [KXStudio/Repository#281]
This makes these CV plugins difficult to use in mod-ui, or in some cases non-functional (CV Meter).

I'd be happy to help with this packaging change but I can't find a public packaging repo.

**Comment by falkTX** [comment]
this is intentional, as the modguis are quite useless for desktop applications.
if you want the MOD (patched) plugins this has a whole setup for it https://github.com/moddevices/mod-live-usb/tree/main/plugins

**Comment by steveb** [comment]
My wish is for kxstudio packaged plugins to have better mod-ui support in general (I have built a zynthian based guitar pedal, but zynthian users like the mod-ui engine for non-guitar applications also).

**Comment by falkTX** [comment]
yeah I understand, and I did that before, but dont think it is a good option.
MOD patches things quite a fair bit, so it is a **lot** of work to keep latest releases plus MOD related patches. I am not doing that anymore, specially since it is possible to build the same exact plugins as MOD uses for x64 now.

**Comment by steveb** [comment]
OK, I think my best bet would be to propose that zynthian switch back to script based installs for some plugins which come from kxstudio, so the overlaying can be done manually

**Comment by falkTX** [comment]
if you want to have the plugins that provide modgui, I think it is best to just manage that separately with a mod-plugin-builder fork.
manual source builds do not scale, and you will deviate from the plugins used in MOD which are untested.
adding extra plugin build projects in mod-plugin-builder would benefit both MOD (which would then help maintenance) and zynthian too (assuming it starts using mod-plugin-builder)

I am quite open to have a zynthian-specific toolchain file, so anyone can build properly optimized plugin binaries for it.
cross-compiling plugins for zynthian (or any arm device) is something that is solved with MPB through the use of ct-ng

**Comment by steveb** [comment]
> if you want to have the plugins that provide modgui, I think it is best to just manage that separately with a mod-plugin-builder fork.

Ah, that is a good idea. I'll have a play and come to zynthian with a proposal.
