### ISSUE TITLE
'Deprecated' repo error

### ISSUE THREAD

**Issue by Munchotaur** [KXStudio/Repository#287]
I'm running MX LInux 21 (based on Debian 11.3).
When upgrading, I see the following error:

```
Reading package lists... Done
E: Repository 'http://ppa.launchpad.net/kxstudio-debian/music/ubuntu bionic InRelease' changed its 'Label' value from 'Music' to 'Deprecated'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```
Have to say that I didn't really achieve enlightenment from the apt-secure manpage. 
Is this a fatal error or will updates continue?

**Comment by falkTX** [comment]
Updates will continue, I am just preparing for new things and setting up the repos accordingly.
You can run this to fix the issue:

```sh
sudo rm -f /var/lib/apt/lists/*
```

I plan to write about this on the kxstudio news very soon

**Comment by pakraticus** [comment]
Commenting out the line for http://ppa.launchpad.net/kxstudio-debian/music/ubuntu
was sufficient.
The safe order of operations is
* Put a new version of kxstudio-repos in http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu that no longer references the music repo
* Update the kxstudio-repos deb on the website
* Mark the music repo as deprecated when the number of accesses goes below a threshold.

Yes, I've gotten this wrong without the benefit of launchpad.
No, I don't know how launchpad makes this more difficult.

**Comment by falkTX** [comment]
Situation has been clarified in https://kx.studio/News/?action=view&url=changes-in-kxstudio-repositories-2
I assume that solves the issue.
