### ISSUE TITLE
repository i386  for 20.04

### ISSUE THREAD

**Issue by ah50x** [KXStudio/Repository#288]
i cannot install winehq-stable on ubuntu focal:
winehq-stable  ->
wine-stable ->
wine-stable-i386:i386  ->
libasound2-plugins:i386 ->
libjack-jackd2-0:i386 (>= 1.9.10+20150825)  | libjack-0.125:i386

winehq on 20.04 uses still i386 
???

**Comment by falkTX** [comment]
yeah, wine does its own repos which allows them to have i386.
launchpad PPAs no longer allows i386 builds, which generates issues.

This might fix things for you:

```
sudo apt-get update
sudo apt-get install libjack-jackd2-0/focal libjack-jackd2-0:i386/focal jackd2/focal
```

**Comment by ah50x** [comment]
On ubuntu 20.04 LTS is jackd2(2:1.9.21-1kxstudio1~focal1) with winehq-stable incompatibel.

Without KXStudio PPAs i found Jackd2 (1.9.12~dfsg-2ubuntu2) and libjack-jackd2-0:i386. 
Version 1.9.12 is kompatibel.
