### ISSUE TITLE
update Tux Guitar for correct build

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#29]
See https://sourceforge.net/p/tuxguitar/bugs/53/#bcd5

Please do the same fix for the version packaged in KXStudio so that everyone has a working install.

**Comment by falkTX** [comment]
so what exactly works for you?
SWT_GTK3=1 or SWT_GTK3=0?

**Comment by wolftune** [comment]
both work just fine as well as running with no argument at all

**Comment by wolftune** [comment]
it seems it just needed to be built with newer SWT and that was all

**Comment by falkTX** [comment]
well, that's the problem in there.
I can't just change something as big as that in the distro and expect everything else to remain fine.
but this seems to be a build-time operation, so perhaps there's something I can do.
I'll compare the resulting builds and see what's going on.

**Comment by wolftune** [comment]
There's also now 1.3.2

**Comment by wolftune** [comment]
Okay, there's a .deb with 1.3.2 for Ubuntu available for download. That could provide some foundation maybe. Problem is that it doesn't include the JACK and fluidsynth support, and installing those packages makes the system try to override tuxguitar with the older version it thinks is newer. So, packaging the 1.3.2 in KXStudio will be the solution.

**Comment by wolftune** [comment]
Tux Guitar 1.4 has been ported to QT! No more GTK I'm guessing! But while I have successfully got a local version of 1.3.2 executable (that they built for me when I was testing before), I can't get their .deb files to install due to conflicts. I'm currently on KDE Neon. Anyway, You can close this if you like, but I thought it might be useful reference for the newer #108 that I just opened for 1.4

**Comment by falkTX** [comment]
Nice, hopefully it's not java anymore either, although I think that might be dreaming too much.
Closing this one then
