### ISSUE TITLE
MacOS Monterry 12.4: Scanning for plugins caused Carla to crash

### ISSUE THREAD

**Issue by GraysonPeddie** [KXStudio/Repository#292]
Carla version: 2.4.3

After installing Calf via Homebrew (`, brew tap david0/homebrew-audio` and `brew install calf`), I tried scanning for Calf plugins but in order to do that, I copied calf.lv2 from `/opt/homebrew/Cellar/calf/lib/` to `~/Library/Audio/Plug-ins/LV2` (I had to create an LV2 directory inside the Plug-ins folder). After I scan the plugins, I get all the Calf plugins listed, but no GUI, so I wanted Carla to scan for the calf.lv2 directory within the `/opt/homebrew/Cellar/calf/lib/` itself.

What I did is I opened the Preferences dialog in Carla, go to Plugin path, choose LV2, Add, and because macOS does not show the list of Unix directories by default, I had to do Cmd+Shift+. in order to show hidden folders. I then navigated to the calf.lv2 within the /opt folder and when I scanned for plugins, Carla crashed.

I then removed the /opt folder from the plugin path in the Preference dialog and the crash keeps happening no matter what.

Please find attached the two files that contained the crash.

[carla-calf-crashed.txt](https://github.com/KXStudio/Repository/files/8846788/carla-calf-crashed.txt)
[carla-calf-crashed-2.txt](https://github.com/KXStudio/Repository/files/8846789/carla-calf-crashed-2.txt)

Please let me know if I can be of further assistance.

**Comment by falkTX** [comment]
Hi. This is the kxstudio repository project, not the carla one. So you reported it in the wrong place.
But in any case, this is a very clear won't fix, as mixing Qt and Gtk event handling from 2 separate sources (Carla official builds and stuff compiled from homebrew) is never going to work right.
In theory building Carla through homebrew, so it uses the same system libs, could work.. but that is unsupported.

**Comment by GraysonPeddie** [comment]
Sorry about that. I did not look for other repositories. I did a Google search and found the one here.
