### ISSUE TITLE
LSP roombuilder 3d display window is blank

### ISSUE THREAD

**Issue by justdnld** [KXStudio/Repository#301]

**Comment by justdnld** [comment]
![Screenshot_20230226_133600](https://user-images.githubusercontent.com/30353358/221438878-9e8b142a-99bd-4449-9cd0-326d59629a4f.png)

**Comment by falkTX** [comment]
lsp-plugins are updated to 1.2.12, this is fixed now by bringing back the lsp-plugins-r3d-glx package
