### ISSUE TITLE
Packaging for 24.04

### ISSUE THREAD

**Issue by milasudril** [KXStudio/Repository#315]
Are there any repositories for Noble available yet?

**Comment by falkTX** [comment]
there are no need for version specific repos, it works as-is. my pc at work is running 24.04 and the kxstudio repos

**Comment by milasudril** [comment]
I did this:

```sh
# Update software sources
sudo apt-get update

# Install required dependencies if needed
sudo apt-get install apt-transport-https gpgv wget

# Download package file
wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_11.1.0_all.deb

# Install it
sudo dpkg -i kxstudio-repos_11.1.0_all.deb
```

Then

```sh
sudo apt update
```

The repositories are not listed

```sh
sudo apt install catia
```

Fails. Am I missing something. Have you moved to flatpacks or snaps?

**Comment by falkTX** [comment]
dont know, those steps worked for me

**Comment by milasudril** [comment]
I guess I should find "noble" in the directory /etc/apt directory?

```
grep -rn kx /etc/apt | grep noble
```

And no hit.

**Comment by falkTX** [comment]
that is not how the repos work, packages are built on older distro version but in a generic way that is forwards compatible.

**Comment by milasudril** [comment]
So how to troubleshoot?

**Comment by falkTX** [comment]
dont know, as I said it worked as-is for me

**Comment by milasudril** [comment]
So I purged the kxstudio-repos_11.1.0_all.deb. Then I run

```
sudo apt update
sudo apt list --upgradeable
```

It then suggests to install from bionic or focal:

```
calf-plugins/bionic 5:0.90.3-1kxstudio3 amd64 [uppgraderingsbart från: 0.90.3-4build2]
carla-bridge-win32/bionic 5:2.6.0~git20240203.2 i386 [uppgraderingsbart från: 2.5.8-0ubuntu5]
carla-data/focal,focal 6:2.5.8-1kxstudio2 all [uppgraderingsbart från: 2.5.8-0ubuntu5]
carla-lv2/focal,focal 6:2.5.8-1kxstudio2 amd64 [uppgraderingsbart från: 2.5.8-0ubuntu5]
carla-vst/focal,focal 6:2.5.8-1kxstudio2 amd64 [uppgraderingsbart från: 2.5.8-0ubuntu5]
carla/focal 6:2.5.8-1kxstudio2 amd64 [uppgraderingsbart från: 2.5.8-0ubuntu5]
flac/focal 6:1.3.3-1kxstudio2 amd64 [uppgraderingsbart från: 1.4.3+ds-2.1ubuntu2]
jalv/focal 6:1.6.6-1kxstudio1 amd64 [uppgraderingsbart från: 1.6.8-1build3]
lilv-utils/focal 6:0.24.14-1kxstudio3 amd64 [uppgraderingsbart från: 0.24.22-1build1]
sndfile-programs/focal 6:1.1.0-2kxstudio7 amd64 [uppgraderingsbart från: 1.2.2-1ubuntu5]
sordi/focal 6:0.16.10-1kxstudio1 amd64 [uppgraderingsbart från: 0.16.16-2build1]
```
Also some of these looks like a downgrade (flac, jalv). By the way, who is the maintainer of kxstudio-repos_11.1.0_all.deb?

**Comment by falkTX** [comment]
that seems correct.
bionic is the older builder that still has a few odd packages, and focal is the newer base where most stuff comes from.

a few downgrades are on me being a bit out of date on the repo packaging, and I am the maintainer for the repos yes.

**Comment by milasudril** [comment]
This is quite confusing. So you build for noble (with gcc-13), but put them in focal?

**Comment by falkTX** [comment]
no, the builder is focal but it works as-is for anything that is newer. there is no need to rebuild these packages

**Comment by milasudril** [comment]
Ok, I see. Maybe you should clarify that.

Note: In general, it is preferred to always use the system default compiler. Sometimes, a bugfix may cause an ABI break.

**Comment by falkTX** [comment]
it uses the default compiler, for focal. rebuilding packages for every single distro is a big maintenance burden and most of the time wasteful. we can build binaries (and packages) in such a way that a single build works everywhere.
this is what the kxstudio repos do, build once in a nice way to then have it work pretty much anywhere that is debian compatible.

**Comment by milasudril** [comment]
So I should not compile my own lv2 plugins with the system compiler and try to load them in your host compiled with an old compiler, unless I only use plain C. Applications may also start to use C++-20 and then gcc-9 would no longer work.

**Comment by falkTX** [comment]
I think you are confusing ABI and API. the libstc++ ABI has been stable since GCC5.1

**Comment by falkTX** [comment]
and backporting GCC to support newer C++ features is not too difficult.

just a few years ago I was building C++11 code in 10.04 with GCC4.9
that setup would still work today if I bothered to keep it, though yes some new codebases would start to be difficult to package.

**Comment by milasudril** [comment]
And sometimes, behaviour is expected to change: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p0952r2.html. But anyways, if you go for keep using an old compiler, go ahead.
