### ISSUE TITLE
Cannot install libarchive-dev without removing Hydrogen

### ISSUE THREAD

**Issue by milasudril** [KXStudio/Repository#32]
I want to read archive files from C, so I would like to install libarchive-dev (version 3.1.2-11build1), but this package is in conflict with libarchvie1 (version 2.8.0-2kxstudio0.1), which is required by hydrogen. Is there a fix for this problem. I am currently on Xubuntu 15.10.

**Comment by falkTX** [comment]
I've rebuilt hydrogen in trusty series, which uses libarchive2.
You should be able to install libarchive-dev now.
