### ISSUE TITLE
Package request: Musescore 2.2

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#35]

**Comment by falkTX** [comment]
is it ok if musescore update is only for >= gcc5 distros?
(debian testing and ubuntu 16.04 or higher)

building musescore for old distros requires manual building and patching to get rid of its web component (can't be used in static builds).

**Comment by wolftune** [comment]
you have to do what's practical with your limited time and energy. I think updating KXStudio overall to fully work with 16.04 and KDE5 is a more valuable thing than getting all updates to older systems. That said, getting rid of Musescore's web component sounds just fine to me, and updating for older systems would be *nice*, but it's not super essential.

**Comment by falkTX** [comment]
I'll try to build it manually then, but if it proves too much work I won't bother.

**Comment by ericfont** [comment]
"building musescore for old distros requires manual building and patching to get rid of its web component"

@falkTX have you put your musescore static build script and patches online anywhere?

**Comment by ciacnorris** [comment]
For me it would be very important to have MuseScore 2.0.3 in the default KXStudio distro, should it be because ms gets backported to KDE4 or because the default KXS distro gets updated to Plasma5 :)
It is a fundamental tool in my workflow and in the workflows of many people I know. I hope you manage to do it

**Comment by wolftune** [comment]
Musescore 2.1 is out and has MAJOR improvements, really valuable, please update!

side note: https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore-stable exists but isn't currently at 2.1 and although it will update my KXStudio install to 2.0.3 for musescore-common, it won't update musescore because of some strange dependency conflict (which has been the case for months in my system).

PLEASE PLEASE this is a major important update!

**Comment by wolftune** [comment]
I'm now having some issues with soundfonts and Musescore libraries updated outside of KXStudio but Musescore is still old. Workaround: use separate soundfont program and plug MIDI output of Musescore into that.

Still, I'd really like to get this update. I understand it may have to wait until the 18.04 KXStudio…

**Comment by ericfont** [comment]
if static building musescore is what is preventing it from being included, I have been talking with the other devs about building musescore statically, and we might actually want to do that, but we haven't gotten around to patching the build system to allow that, so any infor on your patches would be appreciated.

Also, I vaguely remember that it is now possible to build musescore without the webengine component (which was only used in the past for displaying stuff from musescore.com)

**Comment by falkTX** [comment]
The static qt5 was needed to get it to build against older systems, which is not an issue anymore.
I've been focusing on carla and audio plugins, leaving packages on the side for now.

I think I lost my old build files regarding musescore with qt5 static, so I'll very likely have to start fresh.
Since musescore is already in debian, I guess a backport should suffice.

**Comment by wolftune** [comment]
updated to 2.2 for the request, incidentally AppImage they have now supports Jack at least

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For musescore, I recommend to switch over to the new repos, remove the kxstudio package of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

**Comment by mirabilos** [comment]
Also, please contact me for any questions regarding the packaging of MuseScore in Debian, *buntu and the PPAs. Note we offer both MuseScore 2 and 3 (installable in parallel) currently, except for distributions *after* Debian buster (mid-2019), which will ship only MuseScore 3.
