### ISSUE TITLE
Package request: Jamulus

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#36]
Jamulus seems awesome http://llcon.sourceforge.net/

(I independently was contacted by JamKazam people, a proprietary Mac/Windows thing, and I found Jamulus to be the best free/libre/open alternative.

It seems AMAZING with great JACK support etc. but I really need this packaged more reliably, I'm confused about the build process. I'd really like to try this, and if it works well, I'll be using this a lot and promoting it to others.

**Comment by wolftune** [comment]
Okay, this is really  big deal to me, I really need to try this ASAP and I cannot build from source easily because I am getting errors with conflicting dependencies with other KXStudio stuff

`libjack-dev : Depends: libjack0 (= 2:0.124.2~20151211-2~trusty1) but it is not going to be installed`

and trying to install libjack0 threatens to remove a bunch of important stuff

Please, I hope someone can help package this. It really should be included in KXStudio.

**Comment by falkTX** [comment]
I think you need to install libjack-jackd2-dev instead

**Comment by wolftune** [comment]
Thanks, that worked, and building was *very* fast. I guess I should use some of the config things it mentioned though in order to get desktop file and not support CELT (no idea what that is, so assume I don't need it).

The client seems to be working great. This seems like something that would be really easy to package in KXStudio too. I'm tempted to ask how I can contribute to packaging to make this happen…

I just need to figure out how to run it as server for it to get this fully working for me…

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

For contributing a package of it to kxstudio, I would be more than welcome to take it :)
The best way is to get it built in your own private PPA, and after being successful contact me.
I can give you access to the repos, why not
