### ISSUE TITLE
Package Request: OSC2MIDI

### ISSUE THREAD

**Issue by ssj71** [KXStudio/Repository#4]
github.com/ssj71/OSC2MIDI

just for the record, someone else requested it first, so I'm not just tooting my own horn. :) I have no open issues currently so its good to go.

**Comment by rghvdberg** [comment]
+1

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

PS: Sorry...
