### ISSUE TITLE
Package Request: synthclone

### ISSUE THREAD

**Issue by lfzawacki** [KXStudio/Repository#40]
Really useful tool to sample external synthezisers and build SFZs and Hydrogen Drums.

Got it to build with qt4 without major problems.

https://github.com/surfacepatterns/synthclone

**Comment by falkTX** [comment]
I added it to the repos just now.
The gcc5 build needs a little more work (for >= 16.04), I'll handle that tomorrow.

**Comment by falkTX** [comment]
now gcc5 build is ready too. \o/
