### ISSUE TITLE
Package Request: Polyphone

### ISSUE THREAD

**Issue by lfzawacki** [KXStudio/Repository#41]
Soundfont editor with support for loading sfark, sf2, sf3 and exporting to sfz.

Could not build it because of libqcustomplot , but it shoud be doable (?) .

https://sourceforge.net/projects/polyphone
## Edit

Disregard my previous comment. It successfully built with `qmake-qt4 && make` on Linux Mint 17.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
