### ISSUE TITLE
Zita AT-1 0.4

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#45]
The version in the repos currently is 0.2.3, but I see newer at http://kokkinizita.linuxaudio.org/linuxaudio/downloads/

(incidentally, if anyone knows how to contact the author to request a feature, that would be great)

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For AT1, I recommend to use fat1.lv2 plugin based on it
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
