### ISSUE TITLE
Package request: SuperBoucle

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#46]
Hi there

I just discovered SuperBoucle via the LMP website: http://libremusicproduction.com/tools/superboucle
The official website is: http://superboucle.nura.eu/

I just tried it on KXStudio 14.04, it works great (load files, play with controls form GUI, map a controller to some of the controls... It connects to system inputs and outputs automatically in Jack, midi connections are a breeze in Catia...).
I used the latest GitHub release (1.2.0) (do not use the Sourceforge one, I ran into issues): https://github.com/Vampouille/superboucle/releases

After extracting and installing the dependencies listed in the readme file, running the `SuperBoucle.sh` works like a charm.

It would be lovely to have it in the official repos for everyone to install easily, as an alternative/complement to FreeWheeling, SooperLooper and Giada. Is it tricky because it requires some dependencies and then a `pip3 install` command?

Cheers

**Comment by chaocrator** [comment]
wow!
if votes are taken into account, i definitely vote for this one.

**Comment by wargreen** [comment]
The same for me !
:+1:

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
