### ISSUE TITLE
Package Request: open music kontroller apps

### ISSUE THREAD

**Issue by rhetr** [KXStudio/Repository#47]
https://github.com/OpenMusicKontrollers/synthpod
https://github.com/OpenMusicKontrollers/patchmatrix
https://github.com/OpenMusicKontrollers/moony.lv2
https://github.com/OpenMusicKontrollers/orbit.lv2
https://github.com/OpenMusicKontrollers/eteroj.lv2

there are a couple more but these are the main packages.

**Comment by chaocrator** [comment]
if votes are taken into account, i'm voting for these.

**Comment by rhetr** [comment]
[this](https://github.com/OpenMusicKontrollers/patchmatrix/issues/2) might be a problem though

**Comment by falkTX** [comment]
Most of these are packaged now.
Need to see again if all is updated, for KXStudio 18.04

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

The plugin stuff I will port over to the new repos eventually, but not the applications
