### ISSUE TITLE
Package Request: x42-plugins update

### ISSUE THREAD

**Issue by spectromas** [KXStudio/Repository#50]
The kxstudio package is fairly old now and as a result Ardour cannot load some of the plugins, for example http://kxstudio.linuxaudio.org/paste/nAgn0. An update of these plugins should fix the issue.

**Comment by falkTX** [comment]
updated now.

**Comment by spectromas** [comment]
Could we get a version bump to 20160825 at least? There is a bug with Convo.lv2 which was fixed between 22nd and 25th.
