### ISSUE TITLE
package update: Giada 11.2 -> 13.3

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#51]
I saw that the `giada` package has seen 3 releases since 0.11.2 (current version in KXStudio repos). The latest is 0.12.2.
- The source is available on GitHub: https://github.com/monocasual/giada/releases/tag/v0.12.2
- The debs are linked on the forum: http://www.giadamusic.com/forum/giada-0-12-2-flatland-t1392.html

I am testing the 64 bits version on KXStudio 14.04 and it seems to behave better, even taking sample formats that wouldn't work with 0.11.2 (tested mp3, wav, flac and ogg so far).

I thought it would be a good idea to update that?

Changelogs since 0.11.2:

0.12.2 --- 2016 . 06 . 02
- Update RtAudio to version 4.1.2
- Add WASAPI support on Windows
- Sortable plugins list
- Simplify custom RtAudio build and inclusion on Linux
- Fix crashes on startup on OS X El Capitan
- Store position and size of Available Plugins window
- Untangle Channels' code from global variables

0.12.1 --- 2016 . 05 . 06
- Show percentage progress for plugin scan
- Notify if plugins are missing
- Notify if unknown plugins are present
- Fix potential segfault on MasterIn/MasterOut plugins loading
- Proper cleanup of JUCE resources
- Internal refactoring on PluginHost's global variables

0.12.0 --- 2016 . 03 . 07
- Port to JUCE Framework for audio plugin management
- Increase global font size
- Minor UI fixes and cleanups
- Add ability to run tests outside Travis CI
- Switch to C++11
- 64 bit binaries for OS X
- Use new constant for global font size

Cheers! :)

**Comment by stragu** [comment]
Update:

0.13.1 is the latest version.

Changelogs:
    
0.13.0

- Deep file browser refactoring
- Save browser's scroll position and last item selected on opening
- Load patches/projects/samples on double click
- 64 bit builds for Windows
- Prevent deprecated patch from crashing if a plugin is not found in the stack
- Force logger to flush to file on Windows
- Add more default values for windows' dimensions and positions
- Avoid crashes on Configuration panel if no midimaps were selected
- Fix missing keyRelease actions in action editor
- Update JUCE to version 4.2.3
- Don't include JUCE on tests without VST support (GitHub #75)
- Fix compilation errors on GCC 6 (GitHub #82)
- Fix includes on OSX (GitHub #92)
- Fix wrong channel's actions count that prevented 'R' button to be toggled properly
- Fixed a bug that prevented actions on frame 0 to being properly reproduced
- Make Recorder a proper class
- Better naming convention for ActionEditor's children classes
- Source code reorganization

0.13.1

- Input MIDI to MIDI channels/plugins
- Refinements to show/hide 'R' button's dynamics
- Increase piano roll items' height
- Set input volume to max by default
- Start live-recorded sample channels right away
- Avoid potential crashes when loading samples on running channels
- Generate metronome during output post-processing
- Better widgets' layout in Sample Editor
- Lots of source code optimizations and cleanups
- Fix inverted 'R' button's status (GitHub #94)
- Better handling of 'R' button's status when the sequencer is off (GitHub #95)
- Fix non-playing samples if live-recorded and 'R' button is on (GitHub #93)
- Reset button statuses once channels have been freed (GitHub #100)
- Fix missing ASIO and WASAPI APIs on Windows (GitHub #96)
- Missing RtMidi libs on Linux (GitHub #102)
- Fix fade-in/fade-out editing not triggering alert on save (GitHub #101)

**Comment by jhoermann** [comment]
Would be great to see a update.

**Comment by stragu** [comment]
Update: 13.3 is the latest version.

Changelog:

- New Jack implementation with BPM sync and Rewind (GitHub #89)
- Update RtMidi to version 2.1.1
- Improve 'free channel' function (GitHub #105)
- Fix 'Close' button's position inside MIDI input window
- Strip VST folder from Git repository
- New 'Clock' structure for timing operations
- Fix missing tracker reset on 'free channel' function (GitHub #99)

**Comment by stragu** [comment]
[13.4](https://github.com/monocasual/giada/releases/tag/v0.13.4) is the latest version:

Changelog:


    

- Removed support for old ini-based MIDImap files
- Initial support for channel-based MIDI filtering
- New Orphaned MIDI events in Piano Roll editor
- Improve action filtering in Piano Roll editor
- Lots of code refactoring
- New test suite for Action Recorder
- Fix obscure bug when overdubbing actions and a null loop occurs
- Fix "clear all actions" menu refresh when removing items on Piano Roll

**Comment by erwan35** [comment]
Hello,

I would also be happy to have an update :)

Cheers
Erwan

**Comment by falkTX** [comment]
giada updated to 11.4

**Comment by stragu** [comment]
Do you mean 14.5?

**Comment by falkTX** [comment]
err, yes of course. latest right now is 14.5, that I updated to.
