### ISSUE TITLE
[package update] SooperLooper 1.7.0 -> 1.7.3

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#52]
Hi there

I just saw that SooperLooper has seen three minor version releases since 1.7.0 (the repo's current version).

Code is available: http://essej.net/sooperlooper/download.html

Since 1.7.0, here are some of the changes:

 v1.7.3 release -- 11 Dec 2014
Fixed initialization bugs with mute/overdub/replace quantization
v1.7.2 release -- 21 May 2014
Better handles multiple AU instance MIDI port names. Fixed wx compile issues.
v1.7.1 release -- 7 Feb 2014
Now includes 32 and 64 bit AudioUnit plugins, for Mac OS X v10.7 and above. 

Cheers!

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
For sooperlooper, I recommend to switch over to the new repos, remove the kxstudio package of it, and reinstall it again (which will be non-kxstudio version now)
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
