### ISSUE TITLE
Add flac support to klangfalter

### ISSUE THREAD

**Issue by spectromas** [KXStudio/Repository#56]
I don't know if this is within the scope of kxstudio but adding flac file support to klangfalter would be fantastic, IR has this feature.

**Comment by unfa** [comment]
I'm amazed it doesn't have this already! I guess it'd be best to reach out to the developers of Klangfalter, though :)

**Comment by falkTX** [comment]
This might be an issue with the DISTRHO stuff.
Need to investigate what's going on...

**Comment by falkTX** [comment]
Should be fixed now, please confirm.

**Comment by spectromas** [comment]
That has definitely made it see flac files now. I noticed a problem when testing in renoise though (vst version of klangfalter), it doesn't load the impulses correctly. The visual graph at the top turns a darker colour, but there is no slope to indicate the usual tail, it's like the impulse is read as pure noise. There is no wet output though. Seems to be the same when loaded directly in renoise and when loaded in carla rack in renoise.

**Comment by falkTX** [comment]
open a new bug for that.
assuming this one is fixed.
