### ISSUE TITLE
[package update] Qtractor 0.7.8 -> 0.7.9

### ISSUE THREAD

**Issue by stragu** [KXStudio/Repository#59]
New version that brings a few welcome improvements and fixes:

- Audio/MIDI metronome anticipatory offset (NEW)
- Current clip highlighting (NEW)
- SFZ sample file archive/zip bundling (NEW)
- MIDI transpose Reverse tool (NEW)
- MIDI (N)RPN running status and NULL support (NEW)
- MIDI Controllers catch-up algorithm (FIX)
- MIDI track Instrument menu (FIX)
- JACK shutdown and buffer-size changes (FIX)

More: http://www.rncbc.org/drupal/node/1700

Cheers

**Comment by falkTX** [comment]
Updated now.
