### ISSUE TITLE
Timidity using one CPU core upon awake from suspend

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#61]
on Neon w/ T450s laptop. Don't know if it's KXStudio or laptop-specific or something else. When I wake from suspend, timidity is often using a full core (marked as 25% CPU in monitor). Stopping ALSA MIDI bridge and restarting that fixes it. Would setting a MIDI driver in JACK config help maybe?

**Comment by wolftune** [comment]
I just removed timidity-daemon and that did it. I don't think I need timidity for anything besides solfege (and may skip that too). I otherwise just use qsynth whenever I need a GM device.

**Comment by wolftune** [comment]
Had this issue again when I reinstalled the system. As this seems to be something that must be done manually, I suggest KXStudio get updated so that it removes timidity-daemon without needing users to troubleshoot this… just a suggestion

**Comment by falkTX** [comment]
What exactly can be done here? seems like an issue with timidity.
Updating it does not ensure this gets fixed.

timidity is not part of the default install, as far as I know.

**Comment by wolftune** [comment]
Aha! I figured out what's going on (thanks to `aptitude why`). I have Soundkonverter which recommends timidity. Perhaps you could repackage that to not recommend timidity?

**Comment by wolftune** [comment]
Incidentally, removing timidity-daemon solves things. I figured out that I could use Soundkonverter to export .mid to .ogg using Timidity without the daemon installed, but it failed to stop timidity, so it did the same full CPU core issue and had to be killed.

Seems a bug I should report to timidity. But it seems timidity itself can be kept without the daemon and be at least functional…

**Comment by falkTX** [comment]
i am closing this due to not being an issue of a package in the kxstudio repos.
