### ISSUE TITLE
Package request: new Gx plugins

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#62]
https://github.com/brummer10 has more Gx plugins, and I'm especially interested in the bass amp simulation. Of course, I'd like to see it integrated in Guitarix and with MOD stuff etc. Point in the end is that I want myself and other KXStudio users to have these things. Cheers

**Comment by falkTX** [comment]
I completly forgot this was packaged by time ago.
Package name is `gxplugins`.
