### ISSUE TITLE
killall alsa script needs to move for systemd

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#63]
On systems running systemd, the script at /etc/pm/sleep.d/10_kill-alsa-bridge needs to move to /lib/systemd/system-sleep/10_kill-alsa-bridge

Also the line `hibernate|suspend)` needs to change to `pre)`

I don't know which systems use systemd now, but I think it's Ubuntu 15.something on

**Comment by falkTX** [comment]
it should be safe to have the file in 2 places.
in case someone has a wrapper to load the old files, it will just try to kill something twice which is fine.

**Comment by wolftune** [comment]
Oh right, of course. Just putting an appropriate script in each of both places solves everything. Duh

**Comment by wolftune** [comment]
surprised this isn't fixed yet. Easy enough I would think to just add the missing /lib/ file described above so that it's installed by KXStudio repos in all cases. Either it helps or does nothing, won't cause any harm for anyone.

**Comment by falkTX** [comment]
I get distracted with other things, and forget about some.
I appreciate the attention that you bring to the issues, please don't stop.

You have this working for you already, right?
Can you save me some little work and upload the final content of the file here?

**Comment by wolftune** [comment]
Okay, I'll keep pinging you (I totally understand, I feel the same way about others pinging me for similar situations).

Here's the complete file that should be put in /lib/systemd/system-sleep/10_kill-alsa-bridge

```
#!/bin/sh

# kill alsa bridge, may lead to kernel crashes later

case "$1" in
        pre)
                killall -KILL alsa_in alsa_out zita-a2j zita-j2a || true
                ;;
esac
```

**Comment by falkTX** [comment]
Added to latest kxstudio-default-settings package.
