### ISSUE TITLE
Package request: interface software for audio interfaces and more

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#64]
- update to latest [qastools](http://xwmw.org/qastools/) (similar to kmix but has some other features) for qt5 systems
- https://sourceforge.net/projects/qsismixer
- https://github.com/fulup-bzh/AlsaJsonMixer with https://github.com/fulup-bzh/AlsaJsonGateway

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
