### ISSUE TITLE
KDE5: Add back service menus from KDE4

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#69]
I really miss those (audiokonverter, fuseiso, extract...)
Hopefully they can be made to work on KDE5 without too many changes.

**Comment by Houston4444** [comment]
I've made my own ppa containing my services menus compatibles with kde5:
DoAllWithPDF (dependencies too big to be installed by default, but very useful I think)
Image Manipulation (for the moment, fork of kim service menu )
audio conversion (I will rework on this one but it works)
mediainfo
OfficeConverter (convert quickly odt, ods... to pdf, txt, docx, xlsx, etc...)
you can test it with:
`sudo add-apt-repository ppa:houston44/servicemenus`

**Comment by Houston4444** [comment]
test it on xenial, some packages are missing for trusty.

**Comment by wolftune** [comment]
I want pdf and encfs service menus but have failed to get those working so far

**Comment by Houston4444** [comment]
@wolftune , for pdf, did you try from my ppa ?
It didn't works well in Neon because of a new konsole bug  ( https://bugs.kde.org/show_bug.cgi?id=366793 ) I just update, it should works well now.

**Comment by wolftune** [comment]
@Houston4444 that works! The convert and pdf stuff all seems great. Any chance of adding encfs service menu for KDE5 to your PPA?

**Comment by Houston4444** [comment]
why not adding encfs to ppa. I won't work on because I don't use this, but I can simply add one working nice  to ppa. 
This one ?  https://store.kde.org/p/998433/

**Comment by Houston4444** [comment]
humm, quickly tested, it doesn't seems to work very nice... But I must say that I don't really know anything about this. 

Installing encfs from package manager, it says that encfs can't be considered as very sure.

**Comment by wolftune** [comment]
yeah, I know there's some security flaw in encfs, relates, I think, to access to physical machine, not sure. Anyway, I had used it in the past so wanted access to it anyway. Not sure the status. But it worked in KDE4, would be nice to have it again. Probably I and others will eventually move away from encfs…

**Comment by wolftune** [comment]
@Houston4444 your service menu stuff is conflicting with KDE's new updated kdialog which conflicts with kde-baseapps-bin

**Comment by Houston4444** [comment]
Oohh. they are always changing all...No time to see that this coming week, sorry.

**Comment by Houston4444** [comment]
ok. it's repaired in few minutes.

**Comment by wolftune** [comment]
confirmed thanks! still wish I had the encfs service menu back

**Comment by falkTX** [comment]
closing issue due to lack of interest and time for ISO/distro efforts
