### ISSUE TITLE
can't find ardour package in GCC5

### ISSUE THREAD

**Issue by Houston4444** [KXStudio/Repository#71]
Can't understand why. My package ardour (version 1:5.3.5-1kxstudio2v5 downloaded from KXStudio (Extra, GCC5)) seems to have no origin, as if it was installed from a local package.
When I install it on my laptop (with same GCC5 repo), it install  version 1:5.3.5-1kxstudio1v5 (with the wrong .desktop file).

Note: Ardour has been updated to 5.4

**Comment by falkTX** [comment]
Ardour was updated to 5.5.0 just now. Update the software sources and see if this is still an issue.
Thanks.

**Comment by Houston4444** [comment]
yes, it's here. well.
You didn't take a look on mime icons ? I put the good solution here: [](https://github.com/KXStudio/Repository/issues/44)

**Comment by Houston4444** [comment]
https://github.com/KXStudio/Repository/issues/44

**Comment by oopen** [comment]
Fixed by adding -v5 to free and non-free FOR gcc5 & stable repo
like :
```
deb http://kxstudio.linuxaudio.org/repo/ gcc5   free-v5 non-free-v5
deb http://kxstudio.linuxaudio.org/repo/ stable free-v5 non-free-v5
```

- [ ] Please correct them is kxstudio-repos-gcc5_xxx.deb file

**Comment by falkTX** [comment]
Fixed in the new repo setup, "gcc5" is now used for the external packages.
