### ISSUE TITLE
Package Request: LSP Plugins

### ISSUE THREAD

**Issue by unfa** [KXStudio/Repository#74]
# Linux Studio Plugins Project

http://lsp-plug.in/

There's a ton of very nice tools in this plugin suite, with some unique for FLOSS audio like the Phasendetektor. I personally haven't seen anything like this before.

It's calculates delays between two signals - there's another plugin in the set that allows to compensate for that delay. Both plugins work with sample-precision. This seems very useful to phase together tracks where you've got different sources recorded for the same instrument (like guitars from DI, and multiple microphones).

After watching this video I finally understand why my acoustic drum recordings sounded so bad:
https://www.youtube.com/watch?v=j-rNb409GYg

There's also a very nice set of trigger plugins allowing to replace or reinforce drums sounds with samples (or synths I guess - there's MIDI output).

It was kind of possible before, but the elegance in the way these plugins handle this is something unprecedented in linux audio in my opinion.

I think this set would be a great addition to the KX Studio repositories - they're top notch.

**Comment by falkTX** [comment]
These plugins are opensource, so they can't be packaged yet.
Once they opened we can start looking into it.

**Comment by unfa** [comment]
falkTX, You mean "are not opensource", right?
Maybe thery're waiting for donations to release to code like OpenAV Productions did.

However I found some source code for these, but I'm not sure if it's complete:
https://sourceforge.net/p/lsp-plugins/svn/HEAD/tree/trunk/lsp-plugins/

They say it's an opensource project. I'm a bit confused now.

**Comment by sadko4u** [comment]
I've provided access to the source code repository for falkTX, so now it's possible to build LSP Plugins from sources for KXStudio.

Best,
Vladimir

**Comment by wolftune** [comment]
They are now fully open source! https://github.com/sadko4u/lsp-plugins/

**Comment by JazzShapka** [comment]
Hey guys! It realy nice plugins. I want see it in KXStuduo.

**Comment by falkTX** [comment]
I agree they are really nice.
Now with carla supporting those inline displays, I have big reasons to get them packaged.

**Comment by falkTX** [comment]
More than 2 years later, we have it in the repos!

**Comment by falkTX** [comment]
ah, it is `lsp-plugins` package

**Comment by wolftune** [comment]
> More than 2 years later, we have it in the repos!

Yay! But it's only been 6 months since they were freed under legitimate FLO license

For anyone who wants to show the dev that they still support them anyway: https://salt.bountysource.com/teams/lsp-plugins

I might just donate if I find I really use them a lot, but we'll see. I'm first inclined to donate to @falkTX for continuing to maintain KXStudio; cheers

**Comment by falkTX** [comment]
The plugins are quite nice, and developer interested on playing well with Linux and our hosts.

LSP plugins has support LV2 inline displays for example, an LV2 extension made for Ardour.
But a few days ago I added this feature for carla patchbay, it ends up looking quite nice!

![image](https://user-images.githubusercontent.com/1334853/54832781-1cf72680-4cbd-11e9-8cb6-866ef7065937.png)

<3

**Comment by sadko4u** [comment]
One more idea: it would be nice to keep golden ratio between width and high of the inline display if possible.

**Comment by JazzShapka** [comment]
Thank you so much, guys for your work! 👍

**Comment by sadko4u** [comment]
Please also notice that 1.1.7 version of LSP Plugins brings a regression into offline task processing mechanism of LinuxVST and standalone JACK plugin formats that causes improper work of any plugin that utilizes audio files (convolvers, samplers, profilers). The upcoming 1.1.9 release with fixes is planned for the end of this week.

**Comment by sadko4u** [comment]
1.1.9 release is out!

**Comment by falkTX** [comment]
I saw it, updated already :)
