### ISSUE TITLE
amsynth: could not open alsa midi interface

### ISSUE THREAD

**Issue by laconbass** [KXStudio/Repository#75]
## Problem

After installing from kxstudio repos:
    amsynth/wily,now 2:1.6.4-1kxstudio1v5 amd64 [installed]
      two oscillator software synthesizer

I wasn't able to init the MIDI iface. It said: `error: could not open ALSA MIDI interface`. After digging in, and reading [this QA](http://unix.stackexchange.com/questions/177320/amsynth-1-5-1-with-jack-and-alsa-jack-init-failed-error-could-not-open-alsa-m), I though amsyth may be built without alsa support.
## Workaround

Following build instructions at [amsynth github repo wiki](https://github.com/amsynth/amsynth/wiki/BuildingFromSource) (after `apt remove --purge amsynth`):

```
apt install autoconf automake libtool pkg-config libgtk2.0-dev libgtkmm-2.4-dev libjack-jackd2-dev libasound2-dev liblash-compat-dev dssi-dev liblo-dev libsndfile-dev
git clone https://github.com/amsynth/amsynth.git
cd amsynth
./autogen.sh
./configure --with-jack --with-alsa --with-lv2 --with-lash
make
sudo make install
```

I was able to step over the problem, everything worked like a charm.
## Extra: Package update request 1.6 -> 1.7

Since september end, there is a new version available.

https://github.com/amsynth/amsynth/releases/tag/release-1.7.0
https://github.com/amsynth/amsynth/blob/release-1.7.0/NEWS

**Comment by falkTX** [comment]
fixed in 1.8.0 package
