### ISSUE TITLE
Ardour appears to have a bug in its copy of a theme engine

### ISSUE THREAD

**Issue by milasudril** [KXStudio/Repository#77]
This bug is either a package related issue, or a bug in Ardour. But here it is:

I tried to customize the window background for my Work-In-Progress plug-in UI. It looks correct in Carla, and jalv.gtk. Ardour, however, draws GtkFrame shadow with the window background color, when GTK_SHADOW_NONE is in use. Then I got a hint from Ardour startup log, that it cannot find Adwaita. Digging further, I saw that Ardour uses its own (maybe outdated) copy of Clearlooks. Symlinking `/opt/ardour/lib/gtkengines/engines` to `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines` (the system theme engine path), solves the problem. Disabling themes by renaming the engines directory also works.

Before replacing the theme engine
-------------------------------
![bad](https://cloud.githubusercontent.com/assets/734628/19829464/bc15264a-9de2-11e6-9190-1030b53716dc.png)

After replacing the theme engine
-------------------------------
![theme-good](https://cloud.githubusercontent.com/assets/734628/19829465/bc1625e0-9de2-11e6-8f9a-4c600d1a19d6.png)

Code for creating the toggle switch
------------------------------------
	{
	auto sw=gtk_drawing_area_new();
	m_switch=sw;
	gtk_widget_set_size_request(sw,64,64);
	gtk_widget_set_has_window(sw,FALSE);
	gtk_signal_connect(reinterpret_cast<GtkObject*>(sw)
		,"expose_event",G_CALLBACK(switch_draw),this);

	auto eb=gtk_event_box_new();
	gtk_widget_add_events(eb
		,static_cast<int>(GDK_BUTTON_PRESS_MASK|GDK_BUTTON_RELEASE_MASK));
	g_signal_connect(eb,"button-press-event",G_CALLBACK(toggle),this);
	gtk_event_box_set_above_child(reinterpret_cast<GtkEventBox*>(eb),FALSE);
	gtk_event_box_set_visible_window(reinterpret_cast<GtkEventBox*>(eb),FALSE);	
	gtk_container_set_border_width(reinterpret_cast<GtkContainer*>(eb),0);
	gtk_container_add(reinterpret_cast<GtkContainer*>(eb),sw);

	auto switch_box=gtk_aspect_frame_new(caption,0.5f,0.5f,1.0f,TRUE);
	gtk_frame_set_label_align(reinterpret_cast<GtkFrame*>(switch_box),0.5f,0.0f);
	gtk_frame_set_shadow_type(reinterpret_cast<GtkFrame*>(switch_box),GTK_SHADOW_NONE); //I do not want a border here...
	gtk_container_set_border_width(reinterpret_cast<GtkContainer*>(switch_box),0);
	gtk_container_add(reinterpret_cast<GtkContainer*>(switch_box),eb);

	m_box=switch_box;
	parent.widgetAdd(m_box);
	}

**Comment by falkTX** [comment]
you should report this bug to upstream ardour.
kxstudio uses the official ardour builds as-is (just repackaged into a deb file).

**Comment by milasudril** [comment]
Done. I wonder if they update the source for clearlooks, use my symlink, or reject it because external theme engines should not be used. It appears that it requires a clean environment?
