### ISSUE TITLE
package request: Yoshimi

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#78]
active new development, neat stuff, should be included

**Comment by falkTX** [comment]
this is one thing that I'm strong about...
going to be real direct here - I don't like that yoshimi exists and see no reason for it.
development should be merged into zynaddsubfx.

No disrespect for the author, it's not personal.
It's a fork I'd rather see slowly stagnate while its features are ported over to the original project.

So, sorry, but yoshimi is not going to kxstudio repos.

**Comment by wolftune** [comment]
Thanks, I actually agree 100%. I hate that it's a fork. Just practically speaking, how can we get the features ported? And if they aren't ported, we just lose them?

Challenging dilemma here. We don't want to encourage fragmentation.

Anyway, I'll defer to you in this case, and, again, I agree *completely* with the concern. Thanks for the leadership on these issues!

**Comment by falkTX** [comment]
We've talked with the author in the LM forums, as you might know.
He has no interest on stopping yoshimi development.
And I have no interest helping it.

**Comment by wolftune** [comment]
why the heck doesn't he contribute to the original synth?

**Comment by falkTX** [comment]
ask him, not me ;)
