### ISSUE TITLE
Package request: Baudline

### ISSUE THREAD

**Issue by unfa** [KXStudio/Repository#80]
http://baudline.com/

Baudline is a feature-rich standalone tool for analysing sound signals. Very useful for sound reverse-engineering.

It has scientific precision and variety of measurment tools.

**Comment by falkTX** [comment]
Sadly this software cannot be packaged.
See http://baudline.com/download.html

> You are not allowed to distribute this software.
> You are not allowed to reverse engineer this software. 

the source code download is for a very old version.
