### ISSUE TITLE
Package Request: ChucK 

### ISSUE THREAD

**Issue by son0p** [KXStudio/Repository#83]
ChucK :  http://chuck.cs.princeton.edu/

Programming language for real-time sound synthesis, music creation, and on-the-fly MIR ( Music Information Retrieval )

Nice tool to learn audio programming.

**Comment by falkTX** [comment]
The new repos are no longer focusing on applications, only on plugins with very little exceptions.
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
