### ISSUE TITLE
Package request: baudline

### ISSUE THREAD

**Issue by icassina** [KXStudio/Repository#84]
From baudline website (http://www.baudline.com): «Baudline is a time-frequency browser designed for scientific visualization of the spectral domain.  Signal analysis is performed by Fourier, correlation, and raster transforms that create colorful spectrograms with vibrant detail.  Conduct test and measurement experiments with the built in function generator, or play back audio files with a multitude of effects and filters.  The baudline signal analyzer combines fast digital signal processing, versatile high speed displays, and continuous capture tools for hunting down and studying elusive signal characteristics.»

It works with jack and it is great for plugins that don't have a signal analyzer included.

**Comment by falkTX** [comment]
This was proposed 15 days ago, see https://github.com/KXStudio/Repository/issues/80
Copy&pasting the same answer here:

Sadly this software cannot be packaged.
See http://baudline.com/download.html

> You are not allowed to distribute this software.

the source code download is for a very old version.
