### ISSUE TITLE
Carla 32bit missing win32 bridges?

### ISSUE THREAD

**Issue by AVLinux** [KXStudio/Repository#86]
Hi,

I have a forum report that 32 WinVST's cannot be scanned and loaded in 'carla-git' from KXStudio repos. It seems the win32-bridges package is missing from the 32bit repository, the wine dll bridge is present but currently no win32 plugins can be discovered. To be clear all bridges and WinVST functionality is working as expected in Carla 64bit.

Report: http://bandshed.net/forum/index.php?topic=3888.0

**Comment by falkTX** [comment]
the packages are the same same for 32bit and 64bit, so there's no possible missing packages.
both carla-git and carla-bridge-win32 are there. can't you install them?

**Comment by jaZzKCS** [comment]
Posting my reply from the AVL forum in here [Hello, original topic starter here :)]

"Weird thing is, after doing a complete fresh out of the box install of AVLinux32 [not neccessary, can be reproduced with running the LiveISO as well] I realized that - although all carla-git and carla-bridge related packages from KXStudio are preinstalled as mentioned in the manual - the exe files for the plugin discovery are simply missing inside the carla directory, although the packages are installed. (only discovery-native.exe is present) - resulting in the win32/64 discovery "tools" shown as red in the carla plugin refresh window. I found that to be very odd, since in the manual it clearly shows all five tools-checkboxes as green. I was wondering whether I have to install something in addition or maybe configure wine or something, but it seems like the exe files are simply missing, although their corresponding package is definitely installed."

**Comment by AVLinux** [comment]
quick note,

AV Linux uses 'su' not sudo, so run the command without 'sudo' in a Root terminal

`apt-get install --reinstall carla-git carla-bridge-win32 carla-bridge-wine32
`

**Comment by AVLinux** [comment]
Reinstall doesn't work here...

I think there is a missing bridge package in the 32bit repo, Here are screenshots of what appear in freshly reloaded repos with the latest KX-Studio repos enabled:
![carla32](https://cloud.githubusercontent.com/assets/15387844/20806479/153f7202-b7c9-11e6-93f9-1cf7f15c2c5b.png)
![carla64](https://cloud.githubusercontent.com/assets/15387844/20806485/1b8905ec-b7c9-11e6-8ca9-3bd9194757cc.png)

**Comment by jaZzKCS** [comment]
If I see that correctly the carla-bridge-WIN32 (not wine) are missing on the 32bit version?

**Comment by falkTX** [comment]
ignore what synaptic shows, it get confused with multiarch packages.
the question here is - can you run that command to reinstall the packages or not?
if yes, then the packages are there and available just fine.

**Comment by AVLinux** [comment]
Hi,

You're right the package was 'unselected' probably because it never appeared as installable...

That fixes the problem here and WinVST's are now scanned and will load, thanks for the fix, I will look for that in the future and ensure it is fixed on the next ISO release.

```
root@avl32box:/home/isotester# apt-get install --reinstall carla-git carla-bridge-win32 carla-bridge-wine32
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  liblzma1
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  carla-bridge-win32
0 upgraded, 1 newly installed, 2 reinstalled, 0 to remove and 403 not upgraded.
Need to get 1,992 kB/7,748 kB of archives.
After this operation, 8,973 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu trusty/main i386 carla-bridge-win32 i386 2:1.9.5~git20160801 [1,992 kB]
Fetched 1,992 kB in 3s (511 kB/s)               
Selecting previously unselected package carla-bridge-win32.
(Reading database ... 272717 files and directories currently installed.)
Preparing to unpack .../0-carla-bridge-win32_2%3a1.9.5~git20160801_i386.deb ...
Unpacking carla-bridge-win32 (2:1.9.5~git20160801) ...
Preparing to unpack .../1-carla-git_2%3a1.9.5~git20161121_i386.deb ...
Unpacking carla-git (2:1.9.5~git20161121) over (2:1.9.5~git20161121) ...
Preparing to unpack .../2-carla-bridge-wine32_2%3a1.9.5+git20160114.2_i386.deb ...
Unpacking carla-bridge-wine32 (2:1.9.5+git20160114.2) over (2:1.9.5+git20160114.2) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Setting up carla-git (2:1.9.5~git20161121) ...
Setting up carla-bridge-wine32 (2:1.9.5+git20160114.2) ...
Processing triggers for shared-mime-info (1.7-1) ...
Setting up carla-bridge-win32 (2:1.9.5~git20160801) ...
root@avl32box:/home/isotester# 

```

**Comment by patricksebastien** [comment]
On Ubuntu Studio 16.04 the --reinstall command bark:
```
sudo apt-get install --reinstall carla-git carla-bridge-win32 carla-bridge-wine32
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package carla-bridge-win32:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package carla-git
E: Package 'carla-bridge-win32:i386' has no installation candidate
```


Any idea?

**Comment by beniwtv** [comment]
Same here, but with the Carla 64 bit package:
```

The following packages have unmet dependencies:
 carla-bridge-win32 : Depends: carla-bridge-wine32 but it is not installable
```

**Comment by falkTX** [comment]
Try to install carla-bridge-wine32 and see what it says.

**Comment by beniwtv** [comment]
That package seems to be not available for 64 bit :(
http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/carla-bridge-wine/

**Comment by falkTX** [comment]
that's correct.
the wine64 comes from the external, non-ppa repos.
but it's still there.

```
$ apt-cache show carla-bridge-wine64
Package: carla-bridge-wine64
Priority: optional
Section: sound
Installed-Size: 143
Maintainer: falkTX <falktx@gmail.com>
Architecture: amd64
Source: carla-bridge-wine
Version: 2:1.9.5+git20160114
Depends: wine-rt-amd64 | wine-amd64 | wine, libjack-jackd2-0 | libjack0, libc6 (>= 2.19~)
Recommends: carla-bridge-win64
Filename: pool/free/carla-bridge-wine64_1.9.5+git20160114_amd64.deb
Size: 22032
MD5sum: f56ac56d1a07188cc5018dc6388e4f04
SHA1: b3f79fbb71b9a40d07a725ab3e1d5c49298106e0
SHA256: f512f3ff396b9b6005a5c401e94d9a138cf817c7e5c5d9efa895fefaa6095b64
SHA512: 8419e2d25204be998327de68a815a7fcc1faa8be52c46c75329943ee10a9e3a3640c277c719d5742e8b015197e1ad2b5616f73f51d9a15143c9f918f119587c8
Description: carla win64 bridge (wine DLL)
 This package provides the wine DLL needed for the Carla win64 bridge.
Description-md5: c5bf9e3c8a760a37be894751239fd4ef
Multi-Arch: foreign
```

**Comment by beniwtv** [comment]
But the -wine64 one will only load 64 bit Wine plugins, correct?
I was using the -wine32 because I do have a 32 bit plugin that I used.

**Comment by falkTX** [comment]
Yes that's correct. I only replied to you explaining how wine64 package is not really missing.

**Comment by beniwtv** [comment]
Oh, must have misunderstood then, sorry :)
Only the -wine32 is missing, -wine64 is indeed there.

**Comment by falkTX** [comment]
Is it really missing, or not installable due to package conflicts.
What's your output of:
`sudo apt-get install carla-bridge-wine32` ?

**Comment by beniwtv** [comment]
Will let you know the exact output when I get back home (out now), but it's almost the same as @patricksebastien had above, but with wine32 instead of win32.

**Comment by beniwtv** [comment]
Sorry for the delay (been busy these days), here's the output:
```

$ sudo apt-get install carla-bridge-wine32
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package carla-bridge-wine32 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'carla-bridge-wine32' has no installation candidate
```

A cache search:

```
$ sudo apt-cache search carla             
carla-bridge-linux64 - audio plugin host (linux64 bridge)
carla-plugins-lv2 - Dummy package
carla-git - audio plugin host
carla-data - audio plugin host (common data)
carla-lv2 - audio plugin host (LV2 plugin)
carla-vst - audio plugin host (VST plugin)
carla - audio plugin host
carla-dbg - audio plugin host (debug)
carla-bridge-win64 - carla win64 bridge
carla-bridge-win32 - carla win32 bridge
carla-bridge-wine64 - carla win64 bridge (wine DLL)

```

That wit updated repos via apt-get update as of today.

**Comment by johannesmenzel** [comment]
I want to revitalize that threat, cause I have a similar issue and some really nice 32-bit plugins which I want to load on 64-bit machine.

Trying to install carla-bridge-wine32 causes the comment, that...

```
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 carla-bridge-wine32:i386 : Hängt ab von: libjack-jackd2-0:i386 soll aber nicht installiert werden oder
                                           libjack0:i386 soll aber nicht installiert werden
                            Empfiehlt: carla-bridge-win32:i386 soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

```
...these dependencies are missing.

But should (or must) I really install libjack-jackd2-0:i386 and libjack0:i386 on a 64bit machine? Can that possibly muddle up the audio system and former jack configuration?

**Comment by falkTX** [comment]
You *need* 32bit libs if you want to run 32bit software on a 64bit system.
This includes jack2 or jack1 libs too, yes.

**Comment by falkTX** [comment]
start with something easier, non-jack related.
See if you can install libc6:i386 first

**Comment by johannesmenzel** [comment]
```
sudo apt-cache depends libjack0:i386
libjack0:i386
  Hängt ab von [DEPENDS]: libc6:i386
  Hängt ab von: libdb5.3:i386
  Hängt ab von: libdbus-1-3:i386
  Kollidiert mit [COLLIDES]: jackd1:i386
  Kollidiert mit: jackd1:i386
  Kollidiert mit: <libjack-0.116:i386>
    libjack-jackd2-0:i386
  Schlägt vor [RECOMMENDS]: jackd1:i386
  Ersetzt [REPLACES]: <libjack-0.116:i386>
    libjack-jackd2-0:i386
    libjack0:i386

```
Seems like all these packages would be deleted because of the packages libjack0:i386 collides with or replaces?

**Comment by falkTX** [comment]
The packages themselves are fine, I have them installed on all my systems and on the 14.04 KXStudio ISO too.
Again, see if you can install libc6:i386 first

**Comment by johannesmenzel** [comment]
Sorry, I didn't mentioned. Dependencies of libjack0:i386 are already there, including libc6

**Comment by farestp** [comment]
Hello, sorry i am newbie. Why i cannot install carla-git? I have done add the ppa

`E: Unable to locate package carla-git`
`E: Unable to locate package carla-bridge-win32`
`E: Unable to locate package carla-bridge-wine32`

I am using linux mint 18.3

**Comment by falkTX** [comment]
Please don't use this bug report to ask for help...
you need to refresh the package list. `sudo apt-get update` should do it.

**Comment by falkTX** [comment]
@johannesmenzel if you have jack2 installed, you'll need to install libjack-jackd2-0:i386 instead of libjack0:i386.
Try that, see if it makes any difference.

**Comment by farestp** [comment]
@falkTX Oh okay sorry. But thank you

**Comment by luisfdonavarrete** [comment]
@falkTX 
Hi, 
My carla installation used to be work fine but now it's not displaying this
carla-discovery-win32
carla-discovery-win64
on the avaiable tools.
I have carla-discovery-win32 and carla-discovery-win64 already installed, and I tried reinstalling everything all over again but it did not work 
any ideas 
thanks

**Comment by falkTX** [comment]
It's not displaying them because they're now disabled by default.
See http://kxstudio.linuxaudio.org/News/?action=view&url=carla-20-beta6-is-here

**Comment by jotlourenco** [comment]
> 

sudo dpkg --add-architecture i386 ; sudo apt-get update ;
sudo aptitude install carla-bridge-win32

**Comment by lubosz** [comment]
> It's not displaying them because they're now disabled by default.
> See http://kxstudio.linuxaudio.org/News/?action=view&url=carla-20-beta6-is-here

Thanks for pointing this out, I spent some time to notice this. Not very user friendly to hide options like that. It should be grayed out at least.

**Comment by falkTX** [comment]
Not sure what is the state of this ticket anymore, but I am reworking the kx repos, wine is no longer supported 
See https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back
