### ISSUE TITLE
qjackctl pulsing icon uses lots of CPU + fix

### ISSUE THREAD

**Issue by mrbumpy409** [KXStudio/Repository#90]
Qjackctl causes the system tray icon to pulse red when an xrun occurs. Under Plasma 5, this icon animation causes plasmashell's CPU usage to go up a notable amount (10% on my laptop, 2% on my more powerful desktop).

I have solved this problem by compiling qjackctl myself and commenting out lines 3357-3367 in qjackctlMainForm.cpp. This disables the blinking animation. The icon bg will still turn red after an xrun, but it will no longer use up CPU cycles animating the icon.

Perhaps you may wish to make a patch for this for KXStudio?

Here are the lines that are to be commented out of qjackctlMainForm.cpp:
`	#ifdef CONFIG_SYSTEM_TRAY`
`		// XRUN: blink the system-tray icon backgroung...`
`		if (m_pSystemTray && m_iXrunCallbacks > 0) {`
`			const int iElapsed = m_tXrunLast.elapsed();`
`			if (iElapsed > 0x7ff) { // T=2048ms.`
`				QColor color(m_pSystemTray->background());`
`				color.setAlpha(0x0ff - ((iElapsed >> 3) & 0x0ff));`
`				m_pSystemTray->setBackground(color);`
`			}`
`		}`
`	#endif`

**Comment by falkTX** [comment]
upstream added an option that does this.
kxstudio repo package updated to it, so enable it in the settings to do what you want here.
