### ISSUE TITLE
Failed to connect to github.com port 443: No route to host

### ISSUE THREAD

**Issue by gregulatore** [KXStudio/Repository#91]
Any idea why this might have started to happen? I've had to download 5.6 and 5.8 manually on another machine since something broken in the last few weeks.

Err:1 http://kxstudio.linuxaudio.org/repo gcc5/free amd64 ardour amd64 1:5.8.0-1kxstudio1v5                                                       
  Failed to connect to github.com port 443: No route to host
E: Failed to fetch https://github.com/KXStudio/Repository/releases/download/gcc5/ardour_5.8.0-1kxstudio1v5_amd64.deb  Failed to connect to github.com port 443: No route to host

**Comment by magicansk** [comment]
Hi, I got the same issues with you, but I have tried those methods and troubleshot successfully! 
The reason for "No route to host" issues have several to concern:
(I will assume that you have already config the right SSH authenticate to remote servers & service. see more: https://github.com/magicansk/LEARN_Git/blob/master/docs/GIT_NOTES_1.md)
Network: 
1. If your scenario has both OpenSSH-server(for DNS or NAT services)  and OpenSSH-client(for access to your GitHub), then you have to make sure you power on your server(for DNS or NAT services).
2. If you just connect your machine through your router to access the GitHub(no server for DNS or NAT services), then check your router for setting right DNS server.
Firewall:
1. If your OpenSSH-server has the firewall iptables rules, then you have to check both ip address and port.
SSH:
1. SSH service status problem.

**Comment by falkTX** [comment]
Issue with github, assuming fixed. if not, please reopen
