### ISSUE TITLE
Package Request: luppp v 1.1

### ISSUE THREAD

**Issue by m-f-u** [KXStudio/Repository#93]
It would be nice to get the 1.1 release of luppp !

1.1 Feature Release (24-12-16) Features added:

    JACK Sends for FX per track
    Bugfix for clips “walking” out of sync
    Bugfix for clicks sneaking into audio buffers
    Bugfix for fader volumes
    Bugfix Master Returns now working properly again
    UI improvements (look and feel consistent)
    Default loading directories used
    New controller scripts (Akai APK Mini, Launchpad S, Akai APCKey 25)
    Clips can be saved using right-click menu

From https://launchpad.net/~kxstudio-debian/+archive/ubuntu/apps/+build/11876830:
Build status
[MANUALDEPWAIT] Dependency wait on lcy01-30
Missing build dependencies: cairo-static

**Comment by falkTX** [comment]
I had already pushed the build for this, but didn't noticed the dependency issue.
Now available in the repos.
