### ISSUE TITLE
Package Request: Radium music editor

### ISSUE THREAD

**Issue by wolftune** [KXStudio/Repository#94]
https://github.com/kmatheussen/radium has it under the GPL. I recall there being some past issue about it, but I don't see why it couldn't be packaged now.

**Comment by falkTX** [comment]
The author does not support distro packaging afaik, and is even against the
idea.
The archlinux people gave up too afaik

Am 29.03.2017 05:23 schrieb "Aaron Wolf" <notifications@github.com>:

**Comment by falkTX** [comment]
going to close this one as "wont fix".
author is not interested on having his application packaged and redistributed, and I am without patience and time to work around this.
