### ISSUE TITLE
Update zam-audio plugins

### ISSUE THREAD

**Issue by spectromas** [KXStudio/Repository#97]
I can't find a changelog anywhere but I think the dynamic eq was added to 3.8 so it would be fantastic to get a version bump of this package.

**Comment by falkTX** [comment]
zam-plugins now updated to 3.8

**Comment by spectromas** [comment]
Could these be updated to 3.9? There's a bug with dynamic eq which resets the detect frequency when the gui is closed, I believe it was fixed in 3.9.

**Comment by falkTX** [comment]
Update now, I did not know there was a new release.

**Comment by spectromas** [comment]
Thanks, that was quick!
