### ISSUE TITLE
Sync v1 series plugins package with debian

### ISSUE THREAD

**Issue by falkTX** [KXStudio/Repository#99]
Latest debian has separated drumkv1 and drumkv1-common.
We need to do the same *right now*.
Same for samplv1 and synthv1.

**Comment by falkTX** [comment]
See http://ix.io/qd8

hydrogen has the same issue.

**Comment by diqidoq** [comment]
Thanks for your fast reaction on this report in IRC, falkTX.

**Comment by falkTX** [comment]
drumkv1, samplv1 and synthv1 packages are fixed now (synced with debian).
hydrogen and zynaddsubfx coming next.

@diqidoq do you know of any other packages causing issues like this?

**Comment by falkTX** [comment]
The packages that I know to cause issues have now been updated.
